### ISSUE TITLE
where can i find the docs for this library?

### ISSUE THREAD

**Issue by AbdulKalam21** [redouane59/twittered#110]

**Comment by redouane59** [comment]
Hi @AbdulKalam21 , there is a javadoc for the main methods of the project. If you need example, you can have a look to the integration tests (as mentioned on the readme file).
Don't hesitate if you have any specific question.

**Comment by AbdulKalam21** [comment]
Sir where can i  find the javadocs??

**Comment by redouane59** [comment]
It's in the code ! For example : https://github.com/redouane59/twittered/blob/develop/src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java

**Comment by AbdulKalam21** [comment]
Okay thanks :)  +1: 
btw which version do you prefer v2 or v1?

**Comment by redouane59** [comment]
The two versions are complementary. What is now available in v2 is not available in v1 and what is present in v1 is not yet implemented on v2

**Comment by AbdulKalam21** [comment]
Which one to use???

**Comment by redouane59** [comment]
Both !

**Comment by AbdulKalam21** [comment]
how do i know which one i should use?

**Comment by redouane59** [comment]
Just use the `TwitterClient` whatever the implementation is

**Comment by AbdulKalam21** [comment]
Okay thank you for your time, really appreciate it. You can close the issue now

P.S: Create a discord server

**Comment by AbdulKalam21** [comment]
wait does the library only works on JDK15?
Can it work on JDK11?

**Comment by redouane59** [comment]
As explained on the readme, you can use 
```
<dependency>
    <groupId>com.github.redouane59.twitter</groupId>
    <artifactId>twittered-jdk8</artifactId>
    <version>1.15</version>
</dependency>
``` 
in order to use a version before jdk15

**Comment by AbdulKalam21** [comment]
Okay Thanks!
