### ISSUE TITLE
Adding and Deleting Stream Rules

### ISSUE THREAD

**Issue by brianstrauch** [redouane59/twittered#111]
It would be awesome to include functionality for adding and deleting stream rules.

Endpoint: `POST /2/tweets/search/stream/rules`
https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/post-tweets-search-stream-rules

**Comment by redouane59** [comment]
Hi,
are you talking about : 

https://github.com/redouane59/twittered/blob/master/src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java#L152

and 

https://github.com/redouane59/twittered/blob/master/src/main/java/com/github/redouane59/twitter/ITwitterClientV2.java#L160

?

**Comment by brianstrauch** [comment]
Yes! I didn't see that earlier, thanks.
