### ISSUE TITLE
Support of images and other media types

### ISSUE THREAD

**Issue by PhantomYdn** [redouane59/twittered#120]
Hello,

It seems that the client currently supports only text tweets. Do you plan to add support of images and other media types?

**Comment by redouane59** [comment]
Hi,
Just implement it last week : https://github.com/redouane59/twittered/pull/112
I'll release a jdk8 version this week :)
Didn't you plan to at least update your java version to jdk11 ? I recently heard that it will finally be supporter by Android !

**Comment by redouane59** [comment]
Please use 
```
<dependency>
    <groupId>com.github.redouane59.twitter</groupId>
    <artifactId>twittered-jdk8</artifactId>
    <version>1.17</version>
</dependency>
```

**Comment by PhantomYdn** [comment]
Thank you! Do you accept some critics? Seems that you use OkHttpClient just once per request and then forget about it.  There is the recommendation to use one OkHttpClient per running application. You can find it in the [official documentation](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/) and also recommend [this article](https://medium.com/@leandromazzuquini/if-you-are-using-okhttp-you-should-know-this-61d68e065a2b).
Regarding signing: did you try [ScribeJava](https://github.com/scribejava/scribejava)? It provides all required functionality to sign.

**Comment by redouane59** [comment]
Yes of course, I'm not a senior developer so I accept all feedback :)
I will check it and try to create a singleton for OkHttpClient thanks. For the signing part, I just implemented something new last week called `se.akerfeldt.okhttp.signpost` . Implementation is here : https://github.com/redouane59/twittered/blob/cb0601a3117c1189724c5041b3c1af3b48a52460/src/main/java/com/github/redouane59/twitter/helpers/RequestHelper.java#L141 . What new can bring Scribe Java ?

**Comment by PhantomYdn** [comment]
You can use ScribeJava for:

1) Allowing to use multiple types of Http Clients - what ever is suitable for clients. Please check how that's done in ScribeJava
2) As a side effect of p1: all management of Http Clients (singleton vs multi) is done one level down
3) Builtin signing of messages - so no need for extra libraries and etc

P.S. OPoster assume posting to multiple accounts (including twitter accounts), so I personally don't like approach with using OkHttp Interceptors for signing, because in this case that OkHttpClient can be used only for one twitter account.

**Comment by redouane59** [comment]
Ok that's a great thing. I'll try to take a look on it on the next few weeks, but if you have the opportunity to make a pull request, don't hesitate !

**Comment by PhantomYdn** [comment]
@redouane59, please check my PR #126 which is about switching to ScribeJava

**Comment by redouane59** [comment]
> @redouane59, please check my PR #126 which is about switching to ScribeJava

Hi, thank you very much for your PR, I'll try to watch it next week and keep you informed :)

**Comment by redouane59** [comment]
Hey, I close this issue because the main topic is solved. For some parts which are not already implemented, could you create a new one please ? Thanks !
