### ISSUE TITLE
getOAuth1AccessToken NOT working !

### ISSUE THREAD

**Issue by ChallengerCC** [redouane59/twittered#127]
Missing parameter assign(put) in getOAuth1AccessToken(requestToken, verifier):

**parameters.put("oauth_token", requestToken.oauthToken);**

**Comment by redouane59** [comment]
Hi @ChallengerCC , you're right ! We will fix it in the next release :)

**Comment by ChallengerCC** [comment]
Would be also super cool if your library would have a manifest that clarifies what minimum requirements are necessary.
Especially for android development! As your library dont support Android API21 (24 is necessary) because of java 8+.

**Comment by redouane59** [comment]
> Would be also super cool if your library has a manifest, that clarifies what minimum requirements are necessary.
> Especially for android development! As your library dont support Android API21 (24 is necessary) because of java 8+.

If you have an example of it don't hesitate to create a PR. I recently downgrade the project from JDK15 to JDK8 to support Android projects, but are really people still usin JDK7 in 2021 ?
