### ISSUE TITLE
Streaming API and tweet Consumer.

### ISSUE THREAD

**Issue by Greg-M73** [redouane59/twittered#129]
There is a case when the Consumer is triggered on data that is not a JSON tweet but more like a notification for a limitation.

The problem occurs in RequestHelperV2.onResponse(Call call, final Response response), when trying to map the json to a TwitterV2.class, both data & includes properties will be null.

Here is the json received:
```
    {
      "title":"ConnectionException",
      "detail":"This stream is currently at the maximum allowed connection limit.",
      "connection_issue":"TooManyConnections",
      "type":"https://api.twitter.com/2/problems/streaming-connection"
    }
```
When this happens, the stream is disconnected.
You can easily reproduce the problem when starting two twitterclient instance using the same credentials and opening a stream.

I think firing some new ```Consumer<TwitterError>``` would be a good approach, and let the developper handle the error & reconnect the stream.

for example : 
```twitterClient.startFilteredStream(consumer, errorConsumer);```

I'll try to provide a pull request based on your return. (i'm in a rush, so i don't know when).

**Comment by redouane59** [comment]
Hi @Greg-M73  , well seen ! 
This week we will probably merge this huge PR https://github.com/redouane59/twittered/pull/126 and just after it would be awesome if you could submit your :)

Thank you very much !

**Comment by Greg-M73** [comment]
Hi @redouane59 ,

I will try to do so :).
Thank you for your work

**Comment by Greg-M73** [comment]
Here is a draft #139

**Comment by Greg-M73** [comment]
Work done, thx @redouane59  :)
