### ISSUE TITLE
twitterClient.uploadMedia not working?

### ISSUE THREAD

**Issue by joergrech** [redouane59/twittered#135]
Hi, I can't upload media to Twitter using twitterClient.uploadMedia() - is there something special to consider?

After building the twitterClient with the TwitterCredentials builder() and adding the 4 secrets/keys I execute the following code:

```
String filename	= "twitter.png"
File mediaFile	= new File(filename)
assert mediaFile.exists() == true
UploadMediaResponse mediaResponse	= twitterClient.uploadMedia(mediaFile, MediaCategory.TWEET_IMAGE)
```

The resulting mediaResponse exists but has no mediaId (null) and size of 0.

Btw. reading users and tweets works.

**Comment by redouane59** [comment]
Hi @joergrech , just ran the unit test `testUploadMedia` and everything is fine on my side.
```
    UploadMediaResponse response = twitterClient.uploadMedia(new File("C:\\Users\\Perso\\Pictures\\bot.PNG"), MediaCategory.TWEET_IMAGE);
    assertNotNull(response.getMediaId());
```
![image](https://user-images.githubusercontent.com/4500524/107693899-02623800-6caf-11eb-8064-948a8a1c31a8.png)

Did you try to do the same call from postman ? Maybe you can set a break point into `uploadMedia` method in `RequestHelper` class to see the twitter API answer ?

**Comment by joergrech** [comment]
I just used the debugger to track the execution flow and found that I get  a 401 when calling "https://upload.twitter.com/1.1/media/upload.json?media_category=tweet_image" - interestingly the LOGGER.error in logApiError() message does not appear in the IntelliJ console.

And the message says: "Read-only application cannot POST."

Sorry for the confusion - I see if I can change that in the Twitter settings.

**Comment by redouane59** [comment]
Ok so that's just a matter of rights, nothing to see with the lib :)
See https://developer.twitter.com/en/docs/apps/app-permissions
