### ISSUE TITLE
Getter and Setters problem in TwitterClient.java

### ISSUE THREAD

**Issue by AmjedAllaya** [redouane59/twittered#143]
I have cloned twittered project and when I try to use it I get errors from TwitterClient.java, and when I opened it up it found out that a lot of getter and setters are missing

**Comment by redouane59** [comment]
Hi @AmjedAllaya , It's because the project is using [lombok](https://projectlombok.org/), make sure that the [annotation processors](https://www.jetbrains.com/help/idea/annotation-processors-support.html) are on :)

**Comment by redouane59** [comment]
Without any new from your part I consider that your problem is solved...
