### ISSUE TITLE
full  tweets object 

### ISSUE THREAD

**Issue by AmjedAllaya** [redouane59/twittered#145]
hi,
Im trying to get a all the tweets data(media, id ...) with the all the user data (name , profile picture..)
so I wrote this code :
twitterClient.getUserFromUserName(username)
and it returns:
com.github.redouane59.twitter.dto.user.UserV2@62cfe06c

**Comment by redouane59** [comment]
What is you question exactly ?
If you use `getUserFromUserName(String username)`, it will give you the User Object representing the user as the method name indicates. 
If you want to get a tweet information, you should instead use `getTweet(String tweetId)`

**Comment by redouane59** [comment]
@AmjedAllaya does it answer to your question ?

**Comment by AmjedAllaya** [comment]
exactly , When I use one of these i get the following response: 
com.github.redouane59.twitter.dto.user.UserV2@62cfe06c
