### ISSUE TITLE
Possibility to get further information of a tweet

### ISSUE THREAD

**Issue by rahelarnold98** [redouane59/twittered#149]
Hi, would it be possible to extend the Tweet class to be able to get the following information:

- The geographic location of a tweet
- The name of the author of a tweet
- The hashtags of a tweet
- The mentioned URLs in a tweet
- The media of a tweet (picture, video, GIF)

**Comment by redouane59** [comment]
Hi @rahelarnold98 ,

> * The geographic location of a tweet

I think that currently this is not possible, you have to use `tweet.getUser().getLocation()` to have the user location.
For the tweet location, I will try to implement it this week-end.

> * The name of the author of a tweet

Use `tweet.getUser().getName()` 

> * The hashtags of a tweet

Use `tweetV2.getData().getEntities().get("hashtags")` 

> * The mentioned URLs in a tweet

Use `tweetV2.getData().getEntities().get("urls")` 

> * The media of a tweet (picture, video, GIF)

I think this is not possible, a development will probably be needed too, I'll check that.

**Comment by redouane59** [comment]
Missing tweet fields will be accessible from the next release : 
`tweetv2.getAttachments().getMediaKeys()` to get medias ids.
`tweetv2.getGeo()` to get geo-localisation information.

**Comment by rahelarnold98** [comment]
Hi @redouane59 
Thanks a lot for the fast support.

**Comment by redouane59** [comment]
> But by calling tweet.getUser().getName() the only thing that happen is, that UnsupportedOperationException() gets thrown...

Can you tell me how did you get the user ? I think that this is available from `TweetV2` but not `TweetV1`

**Comment by JustinBPhillips** [comment]
Just to follow up - though I've never used github and don't know if this will be seen given it's closed,

TweetSearchResponseV2's data list is of type TweetV2.TweetData, so when a user calls searchForTweetsFullArchive and loops through TweetSearchResponse's getTweets() and calls getUser() then I believe you will reach UnsupportedOperationException().  Perhaps I'm not understanding the code correctly, but I've run into a similar issue as I do not see how to reach TweetV2's Includes information from searchForTweetsFullArchive.

Hopefully this helps.

J

**Comment by redouane59** [comment]
Hi @JustinBPhillips , don't worry I saw your comment. I'm going to debug it now. I'll keep you informed

**Comment by redouane59** [comment]
Ok I see the problem, the Twitter API is returning an object which looks like : 

```
{
   "data":[
      {
         // tweet 1
      },
      {
         // tweet 2
      },
      {
        // tweet X
      }
   ],
   "includes":{
      "users":[
         {
            // user 1
         },
         {
            // user 2
         },
         {
           // user X   
         }
      ]
   }
```
and my method just returns a list of tweets, which is based on the `data` property. 

I don't really like the object that Twitter is returning. To solve the problem, I should maybe return the whole object instead of a `List<Tweet>` an let user consume it with `result.getData()` and `result.getIncludes().getUsers()` .

I will add @SuhemParack into the discussion to have his advice because it's his scope :)

**Comment by JustinBPhillips** [comment]
Fantastic, thanks for looking into this.

While I have you, there are some missing fields in the TweetV2.TweetData class.  Off the top of my head, I think it's missing "source", and "withheld", and Attachments is missing "polls_ids".  Thanks for putting all of this together, I'm looking forward to using this!

**Comment by redouane59** [comment]
> there are some missing fields in the TweetV2.TweetData class

Could you create another issue for this ? I'll try to implement it soon.

**Comment by redouane59** [comment]
> I will add @sparack into the discussion to have his advice because it's his scope :)

For this structure issue, @sparack advised me to create a feedback for his product team [here](https://twitterdevfeedback.uservoice.com/forums/922918-twitter-for-academic-research/suggestions/43492353-list-of-tweet-response-structure) . Please put +1 on it to make the topic going up :)
