### ISSUE TITLE
How to set `media_ids` (and not `media_id`) which doesn't exist in twitter API

### ISSUE THREAD

**Issue by kopax** [redouane59/twittered#154]
Hi all, I was working on a retrofit client for twitter and found your repository listed on twitter website.

It seems this is still under active development, do you know if it's ready for production use? We use spring boot 1.5.9

**Edit**

After a first trial, it's easy to get going with posting a tweet. However, the current `TwitterClient.java` is not yet implementing many methods, for example, it force you to use only one media in `media_ids`.

**Comment by redouane59** [comment]
Hi @kopax , as the twitter V2 endpoints are not all released by Twitter teams, this project will still be in progress during few months/years. However, you can start to use it now, latest versions are stable.

For the `media_ids`, I'm going to check this week if this is something we can implement easily. I'll keep you informed :)
If you check the last issues, a lot of new things were implemented following user feedback ;)

**Comment by redouane59** [comment]
Hi again @kopax , just checked it and you can do it easily : 
Use `twitterClient.postTweet()` method  and add all the media ids you want separated by `,` 
Example : 
`twitterClient.postTweet("Test", null, "12345,67890");
`

**Comment by kopax-polyconseil** [comment]
Hi and thanks for the feedback. I already extended and implemented the method in my app and joining multiple images doesn't seems to attach then all to the tweet (only the first one) so I believe something is missing. Perhaps not with your lib. Thanks for sharing this client !

**Comment by redouane59** [comment]
Yes I just made the test with 2 media ids and it worked fine. After debugging if you see some unexpected behaviours just let me know.

**Comment by redouane59** [comment]
Can I close this issue ?

**Comment by kopax** [comment]
Yes.

Sorry I got completely overwhel with a DC fire incident. Thanks again it now work well.
