### ISSUE TITLE
Request to add Send Direct Message end point

### ISSUE THREAD

**Issue by Suchitainf** [redouane59/twittered#165]
Is there any plan to add direct message related end points?

Sending message events
To send a new Direct Message use POST direct_messages/events/new (message_create). Optionally, you may also attach Quick Replies or media (image, GIF or video).

**Comment by redouane59** [comment]
Hi @Suchitainf ,
As this endpoint is currently not available in V2, it is not planned to develop it in V1 now and migrate few weeks later. We will implement it once the V2 is available. But if you need it before, feel free to develop this endpoint and submit a Pull Resquest :) ! We will review and merge it without any problem.

**Comment by redouane59** [comment]
Is implemented here : https://github.com/redouane59/twittered/pull/210

**Comment by redouane59** [comment]
Solved and available in latest releases :)
