### ISSUE TITLE
Query for calling testSearchTweets30days method

### ISSUE THREAD

**Issue by irisliou33** [redouane59/twittered#171]
We had included the 4 credential keys needed to access the API, but we were confuse why we are unable to use it, since it looks like we included everything required.

When we were trying to use the testSearchTweets30days method, there was an error occurred. I am not sure what we are missing.

![image](https://user-images.githubusercontent.com/72017387/115380123-d316fc80-a204-11eb-8026-aff7105d377a.png)

![image](https://user-images.githubusercontent.com/72017387/115380252-f8a40600-a204-11eb-96eb-3331874f8cf0.png)

Besides, for the development environment name, we were wondering should we put stag or 30days?
![image](https://user-images.githubusercontent.com/72017387/115380338-0a85a900-a205-11eb-8443-62a921b1470d.png)

envName for the method "searchForTweetsWithin30days"
API Key: D3Y3fHVmNVMqfvuy3OpxmiCdu
API Secret Key: x2Ujf2vSNwVX3Jy3QVc7r84TpEedewnkO8ozT6NWq5FssC8c52
Access token: 1380048034289999872-panzdgajwIC5PQ6JnDES7g7GTH24zQ
Access token secret: EqO3gDYX0VB47EQRJBesFMd8Bke8EGwROgenWgw67Vlnl
envName for the method "searchForTweetsWithin30days"

Thank you very much for your precious time !!!

**Comment by irisliou33** [comment]
> We had included the 4 credential keys needed to access the API, but we were confuse why we are unable to use it, since it looks like we included everything required.
> 
> When we were trying to use the testSearchTweets30days method, there was an error occurred. I am not sure what we are missing.
> 
> ![image](https://user-images.githubusercontent.com/72017387/115380123-d316fc80-a204-11eb-8026-aff7105d377a.png)
> 
> ![image](https://user-images.githubusercontent.com/72017387/115380252-f8a40600-a204-11eb-96eb-3331874f8cf0.png)
> 
> Besides, for the development environment name, we were wondering should we put stag or 30days?
> ![image](https://user-images.githubusercontent.com/72017387/115380338-0a85a900-a205-11eb-8443-62a921b1470d.png)
> 
> envName for the method "searchForTweetsWithin30days"
> API Key: D3Y3fHVmNVMqfvuy3OpxmiCdu
> API Secret Key: x2Ujf2vSNwVX3Jy3QVc7r84TpEedewnkO8ozT6NWq5FssC8c52
> Access token: 1380048034289999872-panzdgajwIC5PQ6JnDES7g7GTH24zQ
> Access token secret: EqO3gDYX0VB47EQRJBesFMd8Bke8EGwROgenWgw67Vlnl
> envName for the method "searchForTweetsWithin30days"
> 
> Thank you very much for your precious time !!!

P.S We are using Android Studio since we are trying to develop an mobile app with this API

**Comment by redouane59** [comment]
Hi,

For your first problem, your answer is on the log error message : "invalid api secret". In your example you didn't set any api secret value.

**Comment by redouane59** [comment]
And for your second question, it depends on what you want to do. If you need to access the search endpoint on 30 last days, you should use 30-Days.

**Comment by irisliou33** [comment]
Alritee, thank you for you help!

**Comment by redouane59** [comment]
Is everything solved ? Can we close the issue ?

**Comment by irisliou33** [comment]
> Is everything solved ? Can we close the issue ?

yea, thank you very much!
