### ISSUE TITLE
NullPointerException using getRetweetersId()

### ISSUE THREAD

**Issue by calves07** [redouane59/twittered#172]
Hey,

I have a very simple code, just trying to get a list of retweeters ID, my code looks like this:

`String s = client.getRetweetersId("XXX");`

**client** was initialized like in one of the examples provided:

```
client = new TwitterClient(TwitterCredentials.builder()
                .accessToken(ACCESS_TOKEN)
                .accessTokenSecret(ACCESS_TOKEN_SECRET)
                .apiKey(API_KEY)
                .apiSecretKey(API_SECRET_KEY)
                .build());
```

----
When I run the code, I get a NullPointerException, any thoughts?

```
Exception in thread "main" java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at com.github.redouane59.twitter.TwitterClient.getUserIdsByRelation(TwitterClient.java:144)
	at com.github.redouane59.twitter.TwitterClient.getRetweetersId(TwitterClient.java:211)
```

**Comment by redouane59** [comment]
Can you please provide the id of the tweet you are analyzing ?

**Comment by calves07** [comment]
I tried a couple different IDs and it always failed. One of the IDs I tried was 1384572710248976384

**Comment by redouane59** [comment]
On my side it is working find, I have a result with 41 ids. Are you sure that your credentials are correct ? You can check the error logs, you will probably have an error before the one you shown me.

**Comment by calves07** [comment]
I do have some warnings before that...

```
log4j:WARN No appenders could be found for logger (com.github.redouane59.twitter.helpers.AbstractRequestHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
----
It is also important to note than on my first attempt to run the project, I was getting the error `SLF4J: Failed to load class “org.slf4j.impl.StaticLoggerBinder”` and to overcome this, I added the following dependencies on my pom.xml

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
```
----
I didn't find this importance because I believe this is related to logging. But maybe this is preventing better log messages? Anyway, I'm going to confirm my keys are correct and if it fixes this, I'll update this ticket.

**Comment by redouane59** [comment]
@calves07 don't worry for that, just debug making sure that before calling the endpoint, your twitter credentials are correct on the `twitterClient.getTwitterCredentials()` object

@hypr2771 any suggestion to avoid that users miss the logs ?

**Comment by redouane59** [comment]
@calves07 please double check that your twitter credentials are correctly set up on the `twitterClient.getTwitterCredentials()` object.

**Comment by calves07** [comment]
If you make the request to that post ID, the first UserID will probably be 1206704737833422848.
Can you try getUserFromUserId("1206704737833422848") to see if it gets the user?

**Comment by redouane59** [comment]
working perfectly : 
```
user = {UserV2@2777} 
 data = {UserV2$UserData@2783} 
  id = "1206704737833422848"
  createdAt = "2019-12-16T22:36:54.000Z"
  name = "PEDRONOGUEIRA09"
  displayedName = "Nogueira Jr 💆🏽‍♂️🇬🇹"
  location = null
  url = ""
  verified = false
  profileImageUrl = "https://pbs.twimg.com/profile_images/1381711246626598914/D7aG0N1E_normal.jpg"
  publicMetrics = {UserPublicMetrics@2790} 
  pinnedTweetId = "1379817308990898183"
  description = "U17 🇵🇹|| 1893 💙🇭🇳                                                                   \nI fight for my last name, not my first! 🙇🏽‍♂️\nig:@nogueirajr9 😼🇧🇷"
  lang = null
  isProtectedAccount = false
  following = false
```

**Comment by calves07** [comment]
Well, now my first request to get the retweeters ID is working but then I have another request to get the User and it's coming empty so if I try to get something from the user, there will be a NullPointerException. Anyway, considering your feedback, I'll look into my credentials, maybe my Twitter app has some limitations and cannot access some endpoints or wtv.

**Comment by redouane59** [comment]
It's possible, the `getUserFromUserId()` method is using the API V2, make sure your twitter dev account is able to use these endpoints.

**Comment by calves07** [comment]
I created a project for API v2 and looks like it's working now. Thanks a lot!

**Comment by redouane59** [comment]
Great, have a good night !
