### ISSUE TITLE
Follow endpoint returning null FollowResponse data

### ISSUE THREAD

**Issue by kopax-polyconseil** [redouane59/twittered#179]
Hi @redouane59 , quick question, i want to follow someone using the API, of course I checked before and it use requestHelper v1.

When I run:

```
        FollowResponse f1 = client.follow(t.getUser().getId(), u.getId());
        FollowResponse f2 = client.follow(u.getId(), t.getUser().getId());
```

`f1.data` and `f2.data` are always null, looking at the account I am trying to follow, it's not being followed.

My URl look like `https://api.twitter.com/2/users/250980843/following`, my body look like `{"target_user_id":"3282200682"}`

Do you have a clue what could have been wrong in my code? Thanks in advance

**Edit**

Seems like follow use the v1 helper while v2 url is used:

```
  @SneakyThrows
  @Override
  public FollowResponse follow(String sourceUserId, String targetUserId) {
    String url  = this.urlHelper.getFollowUrl(sourceUserId);
    String body = OBJECT_MAPPER.writeValueAsString(new FollowBody(targetUserId));
    return this.requestHelper.postRequestWithBodyJson(url, new HashMap<>(), body, FollowResponse.class)
                             .orElseThrow(NoSuchElementException::new);
  }
```

**Comment by redouane59** [comment]
Yes the classes are maybe not well named but helper v1 is not related to API endpoints V1.

If you need some code sample don't hesitate to check [integration tests](https://github.com/redouane59/twittered/blob/develop/src/test/java/com/github/redouane59/twitter/nrt/ITwitterClientV2Test.java#L295).

**Comment by kopax-polyconseil** [comment]
Sorry for posting that fast. I solved it using the V1 endpoint, (for those reading https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show , be aware 1.1 params is `user_id` and nothing else). 

I am grateful that you are maintaining this package, it is awesome. Thanks !
