### ISSUE TITLE
Request: Get Display + Expanded Url from UserV2

### ISSUE THREAD

**Issue by HardesFaktor** [redouane59/twittered#180]
Hello,

after searching in the projects code, I haven't found any way to get the expanded and displayed url frpm an user.
Is it possible to add this features under the UserV2 class? Or did I missed something?

What i mean:
<img width="316" alt="twitter_url_example" src="https://user-images.githubusercontent.com/7634094/117455393-6fe8d200-af47-11eb-9469-e949a197bf0a.png">

![image](https://user-images.githubusercontent.com/7634094/117455499-8727bf80-af47-11eb-9cdb-a901c5e154f3.png)

See: https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/user

**Comment by redouane59** [comment]
Hi @HardesFaktor , currently the `getUrl()` method doesn't exist in the User interface, so you have to get the url using `((UserV2) result).getData().getUrl()` . 
But that's a good point I will add it to the next release.

**Comment by redouane59** [comment]
Done, this feature will be present inside the next release (V1.24). You will be able to call `user.getUrl()` for the main url and `user.getEntities()` for all the other entity fields

**Comment by HardesFaktor** [comment]
Thank you! I will then use the getEntities() method in the next release. I already know, that with getUrl() on UserV2 but for my project I also need the displayed + expanded url. Currently I use getUrl() as a placeholder.
