### ISSUE TITLE
Gif cannot be read

### ISSUE THREAD

**Issue by kopax-polyconseil** [redouane59/twittered#183]
I have been trying to upload a gif using `twitterClient.uploadMedia(f, MediaCategory.TWEET_GIF);` and I keep having issue to display it on every browser desktop or mobile I have tried.

It seems the upload is OK, but arrive corrupted. I have tried with an Open source Gif from Giphy and with this rotating earth from wikipedia:

<img src="https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif" style="width: 350px" />

This is what I have : 

![image](https://user-images.githubusercontent.com/77674046/117491933-3462fd80-af71-11eb-8524-dedd38860ab5.png)

I am on linux debian and I have no issue with others twitter client nor gif on twitter

Any clue why is the gif feature broken?

**Comment by redouane59** [comment]
Hi @kopax-polyconseil , honestly I never tested the upload of a gif file. I'm going to try to debug it this week-end, I'll keep you informed.

**Comment by redouane59** [comment]
Issue opened on twitter forum : https://twittercommunity.com/t/issue-with-media-upload-for-gif-files/153856

**Comment by redouane59** [comment]
Hi @kopax-polyconseil ,

We just identified that the endpoint I was using was only dedicated to image files (thanks @mmornati )
To upload gif or videos, other endpoints had to be called (two calls instead of one, for `INIT` and `APPEND`.  See [here](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-init)

Do you feel you can submit a PR with this evolution ?

**Comment by devozs** [comment]
hi guys, any updates / planes to support gif upload?
(this one was closed [https://github.com/redouane59/twittered/pull/184](url))
anyone else was able to work around this issue?
thanks a lot

**Comment by redouane59** [comment]
Hey @devozs , on my side I didn't have time to work on this issue. As Twitter didn't release yet the V2 version of this endpoint, I'll wait that before dedicating some time.
But feel free to submit a pull request if you would like to fix it :)

**Comment by devozs** [comment]
thanks a lot @redouane59 for the overall effort as well as the response!
