### ISSUE TITLE
Limits and pagination

### ISSUE THREAD

**Issue by calves07** [redouane59/twittered#186]
Hey,
I understand the standard limit for requests like getFollowers() is 15 requests per 15 minutes. Each request can retrieve a maximum of 1000 blogs so I guess the max we can get is 15.000 blogs before the limit is reached. But the request doesn't finish until all the data is retrieved so if I'm querying a blog with a lot of followers (let's say 100.000, for example), the request would take more than 1 hour (assuming it will wait for the limit to retrieve the rest of the followers). Is this correct? I would prefer if the method just returned what was retrieved and then I could process part of the data. Maybe the method could have a field like an offset or page to allow the rest of the data to be retrieved later. The way it is right now, if the limit is reached, I won't receive any data so I will reach the limit and won't get anything, it doesn't make much sense.

**Comment by redouane59** [comment]
Hi @calves07, the idea is interesting.

The short-term solution would be to override on your side the method `getFollowers` with something like : 

```
  private List<User> getFollowers(String userId, String token) {
    String     url       =  this.urlHelper.getFollowersUrl(userId);
    List<User> result = new ArrayList<>();
    do {
      String urlWithCursor = url;
      if (token != null) {
        urlWithCursor = urlWithCursor + "&" + PAGINATION_TOKEN + "=" + token;
      }
      Optional<UserListV2> userListDTO = this.getRequestHelper().getRequest(urlWithCursor, UserListV2.class);
      if (!userListDTO.isPresent()) {
        break;
      }
      result.addAll(userListDTO.get().getData());
      token = userListDTO.get().getMeta().getNextToken();
    } while (token != null);
    return result;
  }
```

If some other people feel an interest with it, we could definitively add it to the library.

**Comment by calves07** [comment]
I'll give it a try later!

**Comment by redouane59** [comment]
Hi again,

In the last release I implement the v1.1 getFollowerIds() endpoint. The limit is up to 5000 ids / 15min. If you're using that + okHttpCache it can facilite your work :)

**Comment by calves07** [comment]
Hey,
Thanks but I'm not sure what you mean. I'll look into that when I have some time.

**Comment by calves07** [comment]
Hey,

Still don't know how to achieve this, I understand there is now a better endpoint to use (meaning it's possible to get more followers), however, the method still only finishes after importing all of the followers so we cannot process part of the data, we either wait for it to finish or we don't do anything. I think these methods should be able to receive a pagination parameter to allow for partial processing.

**Comment by redouane59** [comment]
Hey, 

You can totally develop a method as I shown you in your code and instead of calling my method, you call yours. 
If your class contains the TwitterClient, just replace `this.urlHelper` by `this.twitterClient.getUrlHelper()` and same for all needed members.

**Comment by redouane59** [comment]
Or even easier, use the `IdList` class like `getUserIdsByRelation()` method is doing

**Comment by redouane59** [comment]
Hi,

From the v2.1 release, all the twitter v2 endpoints can be called using `AdditionalParameters` object. Setting `recursiveCall` to `false` you will only perform one call and get the `next_token` in the `TweetList` object returned :)

**Comment by calves07** [comment]
Hey,
Glad to see these changes implemented but it still has a problem, in my opinion. Whenever the limit is reached, your AbstractRequestHelper will force the application to sleep for 15 minutes or something like that. In my opinion, it would make more sense to throw a LimitExceededException and let people do whatever they wanted with that information, either wait or process whatever they want with incomplete data, for example.

**Comment by redouane59** [comment]
Hi @calves07 ,

I understand your concern, but to implement this new way of working, it would need a lot of impacting changes in the library core. Why don't you just use `getRateLimitStatus()` method before calling the function ?

**Comment by calves07** [comment]
Hey,
Yep, I actually implemented that already, just mentioning as a suggestion.

**Comment by redouane59** [comment]
Ok I will try to see how to implement it on my side without breaking everything. Maybe having a default setup in the `TwitterClient` can b done easily. I'll keep you informed quickly

**Comment by redouane59** [comment]
Waiting for your feedback about #236 :)

**Comment by calves07** [comment]
I'll let you know after the release.

**Comment by redouane59** [comment]
It's now available :)
