### ISSUE TITLE
No data returned when using searchForTweetsWithin7days

### ISSUE THREAD

**Issue by WORMSTweaker** [redouane59/twittered#187]
Hello! I am using `twitterClient.searchForTweetsWithin7days()` with a few arguments ( `from:WORMSTweaker -filter:replies -RT` ), it was working correctly and I was getting the lastest tweets from this search, but around a month or so ago, it suddenly broke

I tried checking if it was a rate limit issue, I regenerated my keys and tokens multiple times, but nothing helped, and I still get an empty list, no matter what kind of term i'm using:
![idea64_2021-05-13_18-08-34](https://user-images.githubusercontent.com/1344245/118157349-babc8b00-b41a-11eb-9055-873b33abcd0b.png)

As a simple way to check if it was coming from my query or not, I tried it out on python using tweepy:
```python
auth = tweepy.OAuthHandler(twitter_keys['consumer_key'], twitter_keys['consumer_secret'])
auth.set_access_token(twitter_keys['access_token_key'], twitter_keys['access_token_secret'])
tweepy.debug()
api = tweepy.API(auth, wait_on_rate_limit=True)
try:
    api.verify_credentials()
    print("Authentication OK")
except:
    print("Error during authentication")

print(tweepy.API(auth, wait_on_rate_limit=True).rate_limit_status())
search_results = api.search(q="from:WORMSTweaker -filter:replies -RT", count=100)

print( search_results )
```

I tried on both windows and linux, no change there

Any idea why this feature suddenly stopped working? And thanks in advance!

**Comment by redouane59** [comment]
Hi @WORMSTweaker ,

Just watch the error logs :) 

```
08:00:25.609 [main] ERROR com.github.redouane59.twitter.helpers.AbstractRequestHelper - (GET) Error calling https://api.twitter.com/2/tweets/search/recent {"errors":[{"parameters":{"query":["from:WORMSTweaker -filter:replies -RT"]},"message":"There were errors processing your request: Reference to invalid field 'filter' (at position 20), Reference to invalid operator 'filter'. Operator is not available in current product or product packaging. Please refer to complete available operator list at http://t.co/operators. (at position 20)"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"} - 400
``` 

Twitter just doesn't let you use `-filter:replies` .

**Comment by WORMSTweaker** [comment]
Ooooh god why didn't I try that, sorry! Thanks!
I will try to use other operators detailed in the operator list and see what I can do with them
However something surprises me, I do not get such errors messages in my application, did I miss some kind of verbose setting somewhere?

**Comment by redouane59** [comment]
> However something surprises me, I do not get such errors messages in my application, did I miss some kind of verbose setting somewhere?

@hypr2771 any clue about this ? Does external applications have to have a `logback.xml` file to see the lib logs ?

**Comment by redouane59** [comment]
@WORMSTweaker could you try to add it to your `pom.xml` :
```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.30</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.7.30</version>
    </dependency>
``` 
From [this](https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder), it should solve your problem.
Please keep me informed I'll update the documentation :)

**Comment by WORMSTweaker** [comment]
@redouane59 Since I am using Gradle instead of Maven, I had to find an alternative, [here](https://stackoverflow.com/a/59178348)
```
dependencies {
    compile group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.30'
    ...
}
```
After specifying the path to a valid log4j.properties file, using `PropertyConfigurator.configure("log4j.properties");`, I am getting logs!
I hope this will help

**Comment by redouane59** [comment]
Great ! So I guess you can close the issue :)

**Comment by WORMSTweaker** [comment]
Sure! Thanks for the help!
