### ISSUE TITLE
twitterClient.getUserMentions() 401 error

### ISSUE THREAD

**Issue by lsgTwoz** [redouane59/twittered#188]
I am using a translator. Thank you for your understanding.

I am getting a 401 error while using twitterClient.getUserMentions(). 
Are tokens being added normally? twitterClient.postTweet() worked fine.

Even when called with Postman, it worked fine. There was nothing wrong with the token.

![image](https://user-images.githubusercontent.com/83392349/118688949-7e859200-b841-11eb-8695-de62a14b1c63.png)

![image](https://user-images.githubusercontent.com/83392349/118689445-f8b61680-b841-11eb-9e3c-354784d278f5.png)

The version uses 1.23. (using gradle)

**Comment by redouane59** [comment]
Hi,
Yes it is added automatically. On my side the method is working.
You should post on the [twitter dev forum](https://twittercommunity.com/) as far as the problem is not related to the library but to the use of the Twitter API :)

**Comment by lsgTwoz** [comment]
I only added this apiKey and apiSecretKey to the config and there was no error!

When initializing the existing config, the accessToken and the accessTokenSecret were initialized at the same time.
Because getUserMentions was an api in v2, an authentication error occurred because the required Bearer token was not added.


Should the v1 client and v2 client be initialized and used separately? 

```
        return new TwitterClient(TwitterCredentials.builder()
                //.accessToken(AES256Utils.decrypt(iv, accessToken))
                //.accessTokenSecret(AES256Utils.decrypt(iv, secretToken))
                .apiKey(AES256Utils.decrypt(iv, apiKey))
                .apiSecretKey(AES256Utils.decrypt(iv, secretKey))
                .build());
```


--------------------------------
+ The call was successful, but I get an UnsupportedOperationException error.
I have seen the Improve UserV2 object item in version 1.24. Is it related??

```
2021-05-20 11:31:03.434  WARN 22548 --- [io-18080-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: (was java.lang.UnsupportedOperationException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: java.util.ArrayList[0]->com.github.redouane59.twitter.dto.tweet.TweetV2$TweetData["user"])]
```

**Comment by redouane59** [comment]
> Should the v1 client and v2 client be initialized and used separately?

No it shouldn't. I'll debug that tonight, it's possible that this is a bug. I'll keep you inform quickly :)

**Comment by redouane59** [comment]
So strange, it looks like without dates it's ok but when you add dates parameters it gives a 401... Still digging.

**Comment by redouane59** [comment]
I didn't manage to have any answer from twitter teams, the API doesn't gave any clue it's hard for me to debug that :(

**Comment by redouane59** [comment]
Ok I just found the root cause, I'm creating the pull request.

**Comment by redouane59** [comment]
fix will be added to the next release :)
