### ISSUE TITLE
Getting nextToken as null

### ISSUE THREAD

**Issue by Yicong-Huang** [redouane59/twittered#193]
Hi @redouane59,

I am using the V2 FullArchiveSearch API, for some reason I am getting the nextToken as null when querying for a large time period. The following is a sample code I use:

```
private def queryForNextBatch(
      query: String,
      startDateTime: LocalDateTime,
      endDateTime: LocalDateTime,
      maxResults: Int
  ): Unit = {

    val response = twitterClient.searchForTweetsFullArchive(
      query,
      startDateTime,
      endDateTime,
      maxResults.max(10), // a request needs at least 10 results
      nextToken
    )

    nextToken = response.getNextToken
    // apperently, the `nextToken` could be null even if there are more pages. 

    // when there is no more pages left, no need to request any more
    hasNextRequest = nextToken != null

    tweetCache = response.getTweets.asScala
  }
```

**Comment by redouane59** [comment]
Hi @Yicong-Huang ,

Did you try the same from postman ? Do you have the same behavior ?

**Comment by Yicong-Huang** [comment]
@redouane59 No I haven't. It will be hard for me to reproduce this with postman as I am not sure how to loop with the tool. I did test with https://github.com/twitterdev/search-tweets-python/tree/v2 and the same query worked fine.

The query is arbitrary in fact, could use anything that would result in many pages, for example, just "job". The time window I used is from "2017-01-01T00:00:00Z" to "2021-01-01T00:00:00Z". For each "page" I request 500 tweets. The behavior is it will get the first 10 - 20 pages fine (returning a correct `nextToken` for the next page), then it will arbitrarily get stopped during roughly 20 ~ 100 pages because the returned `nextToken` is null. You can check out the linked external PR above from my project which just will retry when getting a null `nextToken` and it can fix the issue, temporarily. 

I did not have log turned on -- I tried but not log4j was not playing well with our project on top.

**Comment by redouane59** [comment]
Ok thanks for the info I'm going to try to debug locally. I'll keep you informed.

**Comment by Yicong-Huang** [comment]
that'd be great! thanks a lot. please let me know if you need any other information

**Comment by redouane59** [comment]
> that'd be great! thanks a lot. please let me know if you need any other information

Ok I just launched it : 

```
twitterClient.searchForTweetsFullArchive("job",
                                                                          ConverterHelper.getDateFromString("201701010000"),
                                                                          ConverterHelper.getDateFromString("202101010000"),
                                                                          500,
                                                                          null);
```

And  obtained 476 results. It looks relevant. Don't you have the same behaviour ?

**Comment by Yicong-Huang** [comment]
this is the first "page" right? I just tested I got 488 results and the `b26v89c19zqg8o3fosqtyl91dfiqw7ouuf10ip9vqmq2l` on the first request.

**Comment by Yicong-Huang** [comment]
This behavior is the same. Then the next loop I supply the nextToken to request for the 2nd "page" of the result, and repeat. This works fine for the first 10 - 20ish iterations.

**Comment by redouane59** [comment]
> This behavior is the same. Then the next loop I supply the nextToken to request for the 2nd "page" of the result, and repeat. This works fine for the first 10 - 20ish iterations.

Ok i'm going to test that

**Comment by redouane59** [comment]
Just created this unit test : 

```
 @Test
  public void testSearchTweetsFullArchive2() {
    int    nbLoops   = 30;
    String nextToken = null;
    for (int i = 0; i < nbLoops; i++) {
      TweetSearchResponse result = twitterClient.searchForTweetsFullArchive("job",
                                                                            ConverterHelper.getDateFromString("201701010000"),
                                                                            ConverterHelper.getDateFromString("202101010000"),
                                                                            500,
                                                                            nextToken);
      assertTrue(result.getTweets().size() > 0);
      nextToken = result.getNextToken();
      assertNotNull(nextToken);
    }
  }
``` 

The test is passing fine, nextToken was never null in 30 iterations.

**Comment by Yicong-Huang** [comment]
Thanks for the effort! I understand such random errors could be hard to reproduce, given that I don't have logs turned on. Do you mind testing with slightly larger `nbLoops` values, so that it's more likely to encounter the issue? Also, I wonder if that relates to the rate limit of V2 endpoints, but I believe you are handling rate limits right?

**Comment by redouane59** [comment]
Hi, 

Just made the same test with 100 iterations instead of 30 and it is still passing.

**Comment by Yicong-Huang** [comment]
Oh, that's weird! I will then try to find a way to enable logging and see what kind of error I am getting. The above test looks handy to use, it will be great if I can reuse it somewhere!

**Comment by redouane59** [comment]
Yes don't hesitate :)

**Comment by Yicong-Huang** [comment]
One possible reason for the original issue could be that the requests are sent too frequently, which hits twitter's rate limit. And under such a situation, it could possibly getting a null next token

**Comment by redouane59** [comment]
Hey @Yicong-Huang , did you try the new release 2.5 ? 
I don't know if the problem is still reproductible. 
The new method name is `searchAllTweets`, it is designed differently, with the use of a new class called `AdditionnalParameter`. I would appreciate your feedback and some update if you still have the problem.

**Comment by Yicong-Huang** [comment]
no not yet. Will be glad to try that out and give feedbacks to you!

**Comment by redouane59** [comment]
Perfect, if you need any support don't hesitate. 
You just need tu set the parameter `resurciveCall` to `false` in `AdditionalParameters` if you want the method to just make one call and then return the `next_token`.

**Comment by Yicong-Huang** [comment]
@redouane59 I was going to try the new release 2.5, very glad to see the recursive call is being handled internally now!

However, I do have some questions regarding using this new `searchAllTweet` endpoint.
1. I don't see how I can specify a start time and an end time for the `searchAllTweet` method? 
2. Also, how frequent are the underlying requests being sent? because it seems like the recursive call would try to send sub-requests as fast as possible, isn't that a concern?

**Comment by redouane59** [comment]
Hi, 

1. inside the `AdditionalParameters` object, you can set a lot of parameter as `startTime`, `endTime` etc.
2. Yes, it will just loop and send a new request each time the previous one is finished.

**Comment by Yicong-Huang** [comment]
ok for 2) I think it will be hard to use like this. my experience is that if you do requests too frequently, reaching twitter's rate limit (max 1 request per second), you will have a cool-down period (e.g., 5 minutes) before you can make another request. For such a recursive loop, requesting as fast as possible might not be a good solution.

**Comment by Yicong-Huang** [comment]
I confirm when I use recursive call with a long run, I got this in log 
```
[09-07-2021 09:34:16.874] [INFO ] [i.g.r.t.h.AbstractRequestHelper.makeRequest(105)] - Rate limit exceeded, new retry in 5m at 09:07 
```

**Comment by redouane59** [comment]
> I confirm when I use recursive call with a long run, I got this in log

Don't worry the method manages the limits, it will sleep and call the endpoint again when it will be authorized :)

**Comment by Yicong-Huang** [comment]
> > I confirm when I use recursive call with a long run, I got this in log
> 
> 
> 
> Don't worry the method manages the limits, it will sleep and call the endpoint again when it will be authorized :)
> 
> 
> 
> (by the way the time is wrong, so strange)

Yeah I am aware of this but I want to avoid waiting for 5 minutes since it's too long for users to wait. Instead I wrapped the logic to ensure maximum 1 request per second and this way it is more efficient to use the API. Greedy approach would return the first serval pages fast, but will hit into this long waits, thus eventually causing the total runtime to be longer.

**Comment by Yicong-Huang** [comment]
If the waiting time is calculate wrong and you can fix it, I'd be glad to push this rate limit handling logic to you 🤣

**Comment by redouane59** [comment]
#> If the waiting time is calculate wrong and you can fix it, I'd be glad to push this rate limit handling logic to you 🤣

Each endpoint has its own limit and usually it is X calls / 15min so I can't imagine how to manage it limiting the time between two calls. Maybe for your case it should be more relevant to set `recursiveCall` to false, use the `nextToken` and finish the process once you've got the exception returned by twitter for the limit ?

**Comment by Yicong-Huang** [comment]
> #> If the waiting time is calculate wrong and you can fix it, I'd be glad to push this rate limit handling logic to you 🤣
> 
> 
> 
> Each endpoint has its own limit and usually it is X calls / 15min so I can't imagine how to manage it limiting the time between two calls. Maybe for your case it should be more relevant to set `recursiveCall` to false, use the `nextToken` and finish the process once you've got the exception returned by twitter for the limit ?

That's what I am doing now. Recursive set to false and manually ensure at most 1 request per second (for FullArchivrSearch endpoint). However, if I ever hit the rate limit, the searchAllTweet will sleep 5 minutes internally before it returns, thus makes it hard for me as a user to avoid such wait.

**Comment by Yicong-Huang** [comment]
Since each twitter endpoints have different rate limits, I would wonder if that's still a good idea to merge all apis to searchAllTweets api. If you merge them, then maybe you need to expose the rate limit to be configurable?

**Comment by redouane59** [comment]
I'm not sure to understand what you mean ?
Basically twitter endpoints return a rate limit error if you call too many times the API within a defined time (it's not about the speed of the calls. If you are limited to 100 calls within 15min, you can do 100 calls in 1sec or 100 calls in 5min, that's exactly the same).
What is really tricky is that sometime you have several ways to make what you want so you should definitively check the API limits in their documentation and choose which endpoint to use and how :)

**Comment by Yicong-Huang** [comment]
hmm, yes I have checked the rate limit on FullArchiveSearch which is 1 call/request per second, and 300 calls in 15 minutes. https://developer.twitter.com/en/docs/twitter-api/rate-limits#v2-limits

However, if I am using your `searchAllTweet` with `recusiveCall` set to false, when hitting a rate limit, the `searchAllTweet` won't return before it finishes sleeping for 5 minutes. How can I avoid this?

**Comment by redouane59** [comment]
Actually is `resursiveCall` is set to false you should get an exception whenever you reach the twitter limit. If you didn't have this behavior there is a bug to fix somewhere.
However what you want to do is really interesting. Maybe I should create another parameter like `throwExceptionIfLimitExceeded` to avoid you implementing on your side the loop which already exists on the library. What do you think ?

**Comment by Yicong-Huang** [comment]
yes, I think that'd be helpful to include a parameter to let the `searchAllTweet` throws an exception when hitting twitter's rate limit! thanks in advance!

**Comment by redouane59** [comment]
Oups I think I already implemented the feature haha
Can you try to set `twitterClient.setAutomaticRetry(false)` before doing your call please ?

**Comment by Yicong-Huang** [comment]
yeah, I confirm it works! thanks!

**Comment by redouane59** [comment]
> yeah, I confirm it works! thanks!

Great !! I'm happy for you :) 

See you !
