### ISSUE TITLE
Add support for attachment_url in tweets

### ISSUE THREAD

**Issue by civ** [redouane59/twittered#194]
If it's possible and I missed it excuse me.
As described in this stackoverflow question: 
[https://stackoverflow.com/questions/29680965/how-do-i-properly-retweet-with-a-comment-via-twitters-api](https://stackoverflow.com/questions/29680965/how-do-i-properly-retweet-with-a-comment-via-twitters-api)

TwitterClient.postTweet needs a variant with an attachment_url param to "embed" another tweet while posting a new tweet as explained above without showing the URL in the tweet text itself. 

     parameters.put("attachment_url", "TweetToRetweetURL");

^Does it.

**Comment by redouane59** [comment]
Hi,
Did you try to just put in the tweet text the url of the second tweet ?

**Comment by civ** [comment]
> 
> 
> Hi,
> Did you try to just put in the tweet text the url of the second tweet ?

You mean putting the url of the tweet I want to retweet into the text of my new tweet? 
That works but it's displayed on Twitter itself differently, you can see that difference in that stackoverflow question above (I just noticed I messed up the link, sorry about that. Works now)
In one case the URL of the retweeted tweet itself is not inside the new tweet's text

**Comment by redouane59** [comment]
Solved, you can now use : 
` Tweet tweet = twitterClient.postTweet("test", null, null, "https://twitter.com/TwitterDev/status/1392465174708187137");`

Once Twitter team release the V2 endpoint I'll provide a cleaner solution :)
