### ISSUE TITLE
Using a stream

### ISSUE THREAD

**Issue by liviuserbanescu** [redouane59/twittered#211]
Hello, I would like to use your library in order to start a filtered stream that will follow some users and some tags. I see that creating the stream is easy, but I don't know how to make the client aware of the list of users to follow (and the list of tags). Could you point me to an example? Thank you!

**Comment by redouane59** [comment]
Hi, just use `tweet.getUser()` to get the user, or  `twitterClient.follow(tweet.getUser().getId()` to follow the related user.

**Comment by liviuserbanescu** [comment]
Thank you! Will try it out

**Comment by redouane59** [comment]
I close the ticket, if you have any issue don't hesitate to re-open it
