### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by calves07** [redouane59/twittered#237]
Hey,
I noticed I cannot serialize a list of UserData, for example. Is this correct and is there a way to easily save the data in a file to import later? I believe if your class implements Serializable, it will work. I can also implement a workaround on my side by creating a serializable object that contains data from your UserData object.

**Comment by redouane59** [comment]
Hi,
Honestly I never tried that. Why can't you serialize this class? Do you have an error or something to share ?

**Comment by calves07** [comment]
Yes, java.io.NotSerializableException

Simple test:
````
        UserV2 user = API.getUserFromUsername("POTUS");
        ArrayList<UserV2> aux = new ArrayList<>();
        aux.add(user);
        Serializer.serialize(aux, "Test_ArrayList_UserV2");
````

If it's a list of other type of object (from my code, for example) it works just fine. Maybe it will work if you simply add "implements Serializable" in your objects.

**Comment by redouane59** [comment]
Yes I should probably implement the same thing that what I already made for Deserialization (see `UserDeserializerV2Test` class).
I'll fix it soon ;)

**Comment by redouane59** [comment]
Ok finally I just had to add `@JsonIgnore` property on some methods throwing exceptions. It will be available in the next release :)
