### ISSUE TITLE
Rate limit exceeded message displaying milliseconds instead of seconds

### ISSUE THREAD

**Issue by calves07** [redouane59/twittered#238]
Hey,

In AbstractRequestHelper, you have:
```LOGGER.info("Rate limit exceeded, new retry in " + 1000L * retryAfter + "s");```
You are multiplying seconds by 1000, displaying milliseconds instead of seconds.

**Comment by redouane59** [comment]
Well seen, I'm going to correct that ;)

**Comment by calves07** [comment]
If you're going to change that, I also suggest displaying the time

**Comment by redouane59** [comment]
About the current time, is it not to set up on your side ? 
For example, with my log configuration I have this message displayed : 
`15:28:12.459 [main] INFO io.github.redouane59.twitter.helpers.AbstractRequestHelper - Rate limit exceeded, new retry in 300s`

**Comment by calves07** [comment]
Well, that's the current time (at the time of logging), I also have that. I'm suggesting to include the time for the reset. Because it's more user friendly to say it resets at 15:35 rather than in 400 seconds, for example.

**Comment by redouane59** [comment]
I see, let me check it :)

**Comment by redouane59** [comment]
``` 
16:00:57.520 [main] INFO io.github.redouane59.twitter.helpers.AbstractRequestHelper - Rate limit exceeded, new retry in 5m at 16:07
``` 
done with latest commit

**Comment by calves07** [comment]
Awesome, thanks.

**Comment by calves07** [comment]
Looks like the time is wrong... I got this message at 21:28, it should indicate 21:33, give or take, not a time from the past.

````[main] INFO io.github.redouane59.twitter.helpers.AbstractRequestHelper - Rate limit exceeded, new retry in 5m at 21:07````

**Comment by redouane59** [comment]
> Looks like the time is wrong... I got this message at 21:28, it should indicate 21:33, give or take, not a time from the past.

So strange, on my side it is still working well : 
```
22:59:43.806 [main] INFO io.github.redouane59.twitter.helpers.AbstractRequestHelper - Rate limit exceeded, new retry in 5m at 23:07
``` 

I don't know what could explain that hmmm..

**Comment by redouane59** [comment]
Hey,
Could you please try this function and told me 
`minutesBeforeNow` in `ConverterHelper` and told me if it works correctly ?
Because I saw in another user log that the endtime was wrong, i cannot understand why it only work on my side :/

**Comment by redouane59** [comment]
Ok I found the issue : https://github.com/redouane59/twittered/pull/261
