### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by calves07** [redouane59/twittered#243]
Hey,
Some inconsistencies I came across:

- There is a getFollowersIds() method but there isn't the equivalent getFollowingIds() even though the logic is pretty much the same, only the URL of the request should be different

- In the following code, the first line will return all IDs even if it needs to do more than one request, but the second one will only return 100 users (making just one request, I assume). Obviously, it's possible for developers to implement a workaround by splitting the first list in lists of 100 IDs but it would make sense if the API followed the same logic (by making more requests if necessary, for the second line, for example)

````
ids = client.getFollowersIds(userId);
users = client.getUsersFromUserIds(ids);
````

**Comment by redouane59** [comment]
Well seen, I'm going to check it soon ;)

**Comment by redouane59** [comment]
> There is a getFollowersIds() method but there isn't the equivalent getFollowingIds() even though the logic is pretty much the same, only the URL of the request should be different

Initially I didn't implement this endpoint because it's part of V1. Unfortunately, his equivalent endpoint in V2 `getFollowers()` only allows 1000x15=15.000 results / 15min vs 5000x15=55.000 / 15min for the V1 one.
The `getFollowingIds()` endpoint is not implemented for 2 reasons : 
1- It's part of V1 endpoints
2- I don't think that much accounts exist with millions of following, so the V2 endpoint should be enough to retrieve this information.

> In the following code, the first line will return all IDs even if it needs to do more than one request, but the second one will only return 100 users (making just one request, I assume). Obviously, it's possible for developers to implement a workaround by splitting the first list in lists of 100 IDs but it would make sense if the API followed the same logic (by making more requests if necessary, for the second line, for example)

That's the way V1 & V2 endpoints work. V1 endpoints were giving ids whereas V2 endpoints now give user objects.

Finally I should maybe just tag `getFollowersIds()`  method as `Deprecated` ?

**Comment by calves07** [comment]
> > There is a getFollowersIds() method but there isn't the equivalent getFollowingIds() even though the logic is pretty much the same, only the URL of the request should be different
> 
> Initially I didn't implement this endpoint because it's part of V1. Unfortunately, his equivalent endpoint in V2 `getFollowers()` only allows 1000x15=15.000 results / 15min vs 5000x15=55.000 / 15min for the V1 one.
> The `getFollowingIds()` endpoint is not implemented for 2 reasons :
> 1- It's part of V1 endpoints
> 2- I don't think that much accounts exist with millions of following, so the V2 endpoint should be enough to retrieve this information.

If getFollowingIds() is part of V1, I assume getFollowersId() is part of V1 as well. This endpoint allows for 15 requests x 5.000 IDs per request = 75.000 IDs. V2 endpoints, which I assume to be getFollowers() and getFollowing() allow for 15 requests x 200 = 3.000 users which is pretty low.

> > In the following code, the first line will return all IDs even if it needs to do more than one request, but the second one will only return 100 users (making just one request, I assume). Obviously, it's possible for developers to implement a workaround by splitting the first list in lists of 100 IDs but it would make sense if the API followed the same logic (by making more requests if necessary, for the second line, for example)
> 
> That's the way V1 & V2 endpoints work. V1 endpoints were giving ids whereas V2 endpoints now give user objects.
> 
> Finally I should maybe just tag `getFollowersIds()` method as `Deprecated` ?


I'm not talking about wether the method returns ID or an object. I'm talking about the fact that one method makes one API request to retrieve just a small part of the data while the other method makes repetitive requests in order to retrieve all the data, this is inconsistent.

**Comment by redouane59** [comment]
> If getFollowingIds() is part of V1, I assume getFollowersId() is part of V1 as well. This endpoint allows for 15 requests x 5.000 IDs per request = 75.000 IDs. V2 endpoints, which I assume to be getFollowers() and getFollowing() allow for 15 requests x 200 = 3.000 users which is pretty low.

Yes As I said the two endpoints are from v1 and allow 15x1000 = 15.000 results / 15min. I'm maybe wrong but I don't think that much people follow several hundred thousand of accounts (event Twitter set a limit). I just thought that using an old endpoint was not the best idea if the V2 could work sufficiently. Let's say that keeping the getFollowerIds v1 endpoint was only relevant because a lot of accounts have several hundred thousand followers which can make the V2 method too slow to process.

> I'm not talking about whether the method returns ID or an object. I'm talking about the fact that one method makes one API request to retrieve just a small part of the data while the other method makes repetitive requests in order to retrieve all the data, this is inconsistent.

This is not right, the two methods will loop to get all the results : 

Method used for `getFollowerIds()` : 
```
  private List<String> getUserIdsByRelation(String url) {
    String       cursor = "-1";
    List<String> result = new ArrayList<>();
    do {
      String           urlWithCursor  = url + "&" + CURSOR + "=" + cursor;
      Optional<IdList> idListResponse = getRequestHelper().getRequest(urlWithCursor, IdList.class);
      if (!idListResponse.isPresent()) {
        break;
      }
      result.addAll(idListResponse.get().getIds());
      cursor = idListResponse.get().getNextCursor();
    } while (!cursor.equals("0"));
    return result;
  }
```

Method used for `getFollowers()` method : 

```
  private UserList getUsersRecursively(String url, Map<String, String> parameters) {
    String   next;
    UserList result = UserList.builder().data(new ArrayList<>()).meta(new UserMeta()).build();
    do {
      Optional<UserList> userList = getRequestHelper().getRequestWithParameters(url, parameters, UserList.class);
      if (!userList.isPresent() || userList.get().getData() == null) {
        result.getMeta().setNextToken(null);
        break;
      }
      result.getData().addAll(userList.get().getData());
      UserMeta meta = UserMeta.builder()
                              .resultCount(result.getData().size())
                              .nextToken(userList.get().getMeta().getNextToken())
                              .build();
      result.setMeta(meta);
      next = userList.get().getMeta().getNextToken();
      parameters.put(AdditionalParameters.PAGINATION_TOKEN, next);
    } while (next != null);
    return result;
  }
```

**Comment by calves07** [comment]
> Yes As I said the two endpoints are from v1 and allow 15x1000 = 15.000 results / 15min.

Incorrect, if we are talking about the endpoint that returns IDs, it's 15 x 5.000 = 75.000 results / 15 minutes.
The limit for V2 endpoints that return users data, is 15 x 200 = 3.000 users / 15 minutes. It's a massive difference, a lot of accounts have more than 3.000 followers or friends (following) so support for V1 endpoint is very nice.
Also, if you already have support for getFollowersIds(), why not implement getFollowingIds() as well? It's pretty much 5 or 6 lines. I actually implemented this locally in my fork so I might even create a PR in this project with that.

> I'm talking about these 2 methods:

````
            result = client.getFollowingIds(userId);
            users = client.getUsersFromUserIds(result);
            System.out.println(result.size());
            System.out.println(users.size());
````
For example, for a specific blog, the first print will be 876 but the second one will be 100. So, in the first method, you're making multiple requests. But in the second one, you're only making one request returing only 100 users. This is the inconsistency that I was mentioning.

**Comment by redouane59** [comment]
You can now use v2.5 :) https://github.com/redouane59/twittered/releases/tag/v2.5
