### ISSUE TITLE
doesn't support Academic Research product , tweet.getUser() always null java.lang.UnsupportedOperationException and need of attribute "source"

### ISSUE THREAD

**Issue by Boby024** [redouane59/twittered#250]
It doesn't support "Academic Research product" such as "maxResult=500"
User detail per Tweet is always empty.
Could be also possible to get the "source" (which device was used to create the tweet)

**Comment by redouane59** [comment]
Hi @Boby024 , can you precise which method you are calling ?
Thanks !

**Comment by Boby024** [comment]
Hi @redouane59,
I used "searchForTweetsFullArchive"

**Comment by redouane59** [comment]
Ok I see.
Currently the Twitter API doesn't return the user information inside the Tweet object for this endpoint.
I already posted a feedback about this bad structure in Twitter dev feedback forum [here](https://twitterdevfeedback.uservoice.com/forums/922918-twitter-for-academic-research/suggestions/43492353-list-of-tweet-response-structure). It would be useful if you +1 this.

What I could do waiting for any change on the Twitter side is to make evolve the `TweetList` object and add the `includes` structure to be able to find related user there. What do you think ?

I'll check to add source too.

**Comment by redouane59** [comment]
Fix will be available in the next release 2.5 in the following days :)

**Comment by Boby024** [comment]
@redouane59  thanks for the feedback and the future improvement.
please keep also in mind to enhance 100 to 500 the "maxResult" parameter.

**Comment by redouane59** [comment]
> please keep also in mind to enhance 100 to 500 the "maxResult" parameter.

Is it allowed ? I just put back 100 because the API gave me an error saying the `max_result` param should be between 10 and 100.

**Comment by redouane59** [comment]
Hmmm don't know what happened, i don't have anymore the error, I just put back 500.

**Comment by Boby024** [comment]
I got the same error again:
{"errors":[{"parameters":{"tweet.fields":["attachments,author_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,source,text,withheld,context_annotations,conversation_id,reply_settings"],"max_results":["500"]},"message":"when requesting `tweet.fields=context_annotations` `max_results` must be less than or equal to `100`"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"} - 400

**Comment by Boby024** [comment]
here you can see a proof above 500 "maxResult" from a Twitter staff:
https://twittercommunity.com/t/api-twitter-v2-academic-research/156497/5

**Comment by redouane59** [comment]
> I got the same error again:

Hmmm so strange, are you using the right credentials ?

**Comment by redouane59** [comment]
Oh ok so the problem is related to `context_annotations` field...

**Comment by Boby024** [comment]
I couldn't find this method "searchAllTweets"

**Comment by redouane59** [comment]
> I couldn't find this method "searchAllTweets"

Which version are you using ? Please update your pom and use the latest one :)

**Comment by Boby024** [comment]
I'm actually using <version>1.26</version>
which is the newest?
https://mvnrepository.com/artifact/com.github.redouane59.twitter/twittered

**Comment by redouane59** [comment]
> which is the newest?
The last release is 2.4 and all these fixes will be included in the version 2.5

**Comment by Boby024** [comment]
thanks

**Comment by redouane59** [comment]
You can now use v2.5 :) https://github.com/redouane59/twittered/releases/tag/v2.5
