### ISSUE TITLE
Error when using searchAllTweets() with parameter "recursiveCall" set to true

### ISSUE THREAD

**Issue by ckakalou** [redouane59/twittered#251]
The searchAllTweets() method throws an error when setting the "recursiveCall" parameter to true: 

`ERROR AbstractRequestHelper - (GET) Error calling https://api.twitter.com/2/tweets/search/all {"title":"Unsupported Authentication","detail":"Authentication with OAuth 1.0a User Context is forbidden. Please, make the request with OAuth 2.0 Bearer Token authentication.","type":"https://api.twitter.com/2/problems/unsupported-authentication"} - 403`

This however does not happen when "recursiveCall" is set to false.

I should note that I am using credentials issued for the Academic Track.

**Comment by redouane59** [comment]
Hi @ckakalou , thanks for the issue. I'm going to check that tonight or tomorrow. I'll keep you informed quickly.

**Comment by redouane59** [comment]
It's ok, the problem should be solved now. The fix will come with the next release 2.5 :)

**Comment by redouane59** [comment]
You can now use v2.5 :) https://github.com/redouane59/twittered/releases/tag/v2.5
