### ISSUE TITLE
searchAllTweets doesn't work well

### ISSUE THREAD

**Issue by Boby024** [redouane59/twittered#256]
When calling "searchAllTweets" the message below is given 

(GET) Error calling https://api.twitter.com/2/tweets/search/all {"title":"Unsupported Authentication","detail":"Authentication with OAuth 1.0a User Context is forbidden. Please, make the request with OAuth 2.0 Bearer Token authentication.","type":"https://api.twitter.com/2/problems/unsupported-authentication"} - 403

But it worked well when calling i.e getTweet or getUserFromUserId
How could I fix it?

**Comment by redouane59** [comment]
Duplicate of https://github.com/redouane59/twittered/issues/251
Will be solved in the next release this week

**Comment by Boby024** [comment]
@redouane59  thanks!
