### ISSUE TITLE
Allow filter with language

### ISSUE THREAD

**Issue by Boby024** [redouane59/twittered#268]
I wanted to ask if it would be possible to filter with lang (i.e: en, es, etc ...) ?
Because for my project I would sometimes need to crawl only tweets in English or in German.

**Comment by redouane59** [comment]
Hi @Boby024 ,
As explained on the twitter documentation, you can use various operator inside your search query.
See : https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query
ex: `(happy OR happiness) lang:en`

**Comment by Boby024** [comment]
@redouane59 thanks
