### ISSUE TITLE
How to obtain Entities attached to a given Tweet object?

### ISSUE THREAD

**Issue by rzo1** [redouane59/twittered#271]
Hi  @redouane59 ,

thanks for providing an alternative library to twitter4j (which seems to be dead...)

I might be wrong, but I couldn't find code to obtain the `entities` attached to a certain `Tweet` with the library? Am I right?

For v1.1 I am basically interested in the `entities` and the related index positions as described [here](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview) and [here](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities).

For v2.2 it looks pretty similar: [here](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet).

So I am wondering:

- Not yet implemented? 
- Looks like [v1 API](https://github.com/redouane59/twittered/blob/develop/src/main/java/io/github/redouane59/twitter/dto/tweet/TweetV1.java) is not implemented, yet? Right?

Maybe you can summarize which parts of twitterd are still WIP ?

Thanks & Gruss
Richard

**Comment by redouane59** [comment]
Hi @rzo1 ,

`getEntities()` method is not part of the `Tweet` interface,  nobody asked it before but you're right, it should be there. I'll add it on the next release.

Currently you can use `((TweetV2)tweet).getData().getEntities()` to have it. Please confirm to me that this is working.

**Comment by rzo1** [comment]
Thanks for the fast response.

I think, it would be neat to have the `entites` as fully parsed DTOs (annotations, hashtags, cashtags, mentions, urls) to avoid doing JSON parse magic on the client side. wdyt?

**Comment by redouane59** [comment]
Yes that's true, it was just implemented like this by lack of time. If you want to do it don't hesitate to submit a PR, otherwise it will wait a little bit more :)

**Comment by rzo1** [comment]
Think, this is fixed now.
