### ISSUE TITLE
Under which license is twittered distributed?

### ISSUE THREAD

**Issue by rzo1** [redouane59/twittered#275]
We have the **POM** file, which states Apache Software License

https://github.com/redouane59/twittered/blob/8324c5e07106ed10cb0f1db60f4e5cd3d9881d58/pom.xml#L149

and we have a LICENSE file in the source tree

https://github.com/redouane59/twittered/blob/develop/LICENSE

Can you clarify on the license?

Personally, I would prefer the ASL version.

**Comment by redouane59** [comment]
Hey,
I'm really not expert in license. Could you push a valid model to replace the current LICENCE file and be iso with the pom ?
I just want the library to be free but without any warranty or constraints on my side. Is ASL in this way ?

**Comment by rzo1** [comment]
Yes. You can find more information here: https://en.wikipedia.org/wiki/Apache_License
I will prepare a related PR to switch to ASL.
