### ISSUE TITLE
Pagination doesn't work well

### ISSUE THREAD

**Issue by Boby024** [redouane59/twittered#280]
When putting "searchAllTweets" in the "do-while" it stop after the first call, i.e when the second is built with just "next_token" and/or "sinceId" it does work (output always null". 
Because I want to build my own "getTweetsRecursively" with some extra process in connection with my database.
can you @redouane59 please explain to me how to solve it?

**Comment by redouane59** [comment]
Hey, did you just use the `AdditionnalParameter` argument ? You can set `recursiveCall` to true if you want it to loop.

**Comment by redouane59** [comment]
Can you please leave here some code and logs if you have them.

**Comment by redouane59** [comment]
@Boby024 is it fixed ? If not please give me an update :)

**Comment by Boby024** [comment]
String newestId = null;
        String next;
        AdditionalParameters additionalParameters = AdditionalParameters.builder().recursiveCall(false).maxResults(100).startTime(searchTerm.getSearchFrom()).endTime(searchTerm.getSearchUntil()).build();
        do {
            System.out.println(additionalParameters.toString());
            TweetList tweetList = twitterClient.searchAllTweets(searchTerm.getTerm(), additionalParameters);

            if (tweetList == null || tweetList.getData() == null) {
                break;
            }

            result.add(tweetList);
            if (newestId == null) {
                newestId = tweetList.getMeta().getNewestId();
            }
            next = tweetList.getMeta().getNextToken();
            additionalParameters = AdditionalParameters.builder().recursiveCall(false).maxResults(100).nextToken(next).sinceId(newestId).build();
     
            
        } while(next != null);

**Comment by Boby024** [comment]
sorry for the late reply.

**Comment by redouane59** [comment]
Hmm I'm actually having the same behaviour. Did you try to make the same calls from postman ? Is it working ?

**Comment by Boby024** [comment]
I also tested it without "sinceId" (just with "next_token") but it just stopped after the first request.

**Comment by redouane59** [comment]
Strange, on my side it was working.
Please write here your **full code** with the values to let me run it directly in a unit test. On parallel please try it in Postman and confirm to me that the behaviour is different.
Thanks !

**Comment by Boby024** [comment]
private List<TweetList> getTweetsRecursively(TwitterClient twitterClient, SearchTerm searchTerm) {
        List<TweetList> result = new ArrayList<>();
        String newestId = null;
        String next;
        AdditionalParameters additionalParameters = AdditionalParameters.builder().recursiveCall(false).maxResults(100).startTime(searchTerm.getSearchFrom()).endTime(searchTerm.getSearchUntil()).build();
        do {
            TweetList tweetList = twitterClient.searchAllTweets(searchTerm.getTerm(), additionalParameters);
            if (tweetList == null || tweetList.getData() == null) {
                break;
            }

            result.add(tweetList);
            if (newestId == null) {
                newestId = tweetList.getMeta().getNewestId();
            }
            next = tweetList.getMeta().getNextToken();
            additionalParameters = AdditionalParameters.builder().recursiveCall(false).maxResults(100).sinceId(newestId).nextToken(next).build();
        } while(next != null);

        return result;
}

**Comment by Boby024** [comment]
here is the part where I try to get the tweets

**Comment by Boby024** [comment]
it works now
the parameter request  wasn't gut 
here: how to perform it: https://developer.twitter.com/en/docs/twitter-api/pagination

**Comment by redouane59** [comment]
So there is no bug ? If so, could you close the issue ?

**Comment by Boby024** [comment]
we can close this issue now :)
