### ISSUE TITLE
post tweet with location (Geo, coordinates, latitude and logitude)

### ISSUE THREAD

**Issue by logoff** [redouane59/twittered#287]
Hi.

I have been reading the examples and the code, and I didn't find if it's possible to publish a tweet with Geo data (latitude and longitude). Twitter API v1 allows it in the standard POST (https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update). Is it possible?

Regards.

**Comment by redouane59** [comment]
Hello @logoff ,

Yes I never implemented it and it was never asked before. As this endpoint is still in V1, I won't develop any new feature on it but feel free to submit a pull request if you really need it :)

Thanks !

**Comment by logoff** [comment]
Hi.

Unfortunately, now I have no spare time, but it seems that the library is pretty well-designed and should not be so hard. I have seen already some data model classes with geo information.

Thanks for your answer.

**Comment by redouane59** [comment]
Yes sorry I don't have so much spare time too right now but as soon as the V2 endpoint will be release I'll take time to implement it too.
