### ISSUE TITLE
User: created_at always null and "profil_image_url"

### ISSUE THREAD

**Issue by Boby024** [redouane59/twittered#293]
I tested with my python script and the value "created_at" of "user" was given.
Also "profil_image_url" value is not given 
Could you check them, please?

**Comment by redouane59** [comment]
These two fields are currently supported by the library. Could you share with me which method you used please ?
thanks

**Comment by Boby024** [comment]
I used this method "searchAllTweets"

**Comment by redouane59** [comment]
Ok let me check that :)

**Comment by redouane59** [comment]
Ok if you search tweets, you will be able to find the tweet informations.
For example, `searchAllTweetsResult.getData().get(0).getCreatedAt()` will give you an answer.
But if you need information about the user, you have to get the `authorId` and then call the getUser method...

I already created this issue https://github.com/twitterdev/open-evolution/issues/6 hoping that Twitter API team will make an evolution on this subject.

**Comment by Boby024** [comment]
yes I already used it to get the parameter of tweet "createdAt"
tweetList.getIncludes().getUsers().get(0).getDateOfCreation() give  always "null".

**Comment by redouane59** [comment]
Can you give me the id of the related tweet please ?

**Comment by redouane59** [comment]
Looking for the expansion for this endpoint [in the doc](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all), I don't think that you can get all these data directly. I guess you should make another call from the tweet author id

**Comment by redouane59** [comment]
Ah wait, maybe the url is wrong and should include `user.fields`, let me check that

**Comment by Boby024** [comment]
This issue will also be solved with the next release next week ?

**Comment by redouane59** [comment]
Yes I will probably release it next week or the week after as maximum

**Comment by Boby024** [comment]
thanks 👍

**Comment by redouane59** [comment]
2.9 released
