### ISSUE TITLE
NullPointerException when retrieving pinned tweet for cases where there is no pinned Tweet

### ISSUE THREAD

**Issue by antoniolmc83** [redouane59/twittered#295]
Hi 
I was trying out with my own account (which does not have a pinned tweet), and I got a NullPointerException for getPinnedTweet function.

User user   = twitterClient.getUserFromUserName("LmcAntonio");
System.out.println( String.format("Pinned Tweet: %s  ", user.getPinnedTweet()));

Version 1.26 (The latest one found in Maven repository)
 'com.github.redouane59.twitter:twittered:1.26'

**Comment by redouane59** [comment]
Hi,
You're right. Fixing it.
