### ISSUE TITLE
Can i set proxy?

### ISSUE THREAD

**Issue by shiwangsimba** [redouane59/twittered#300]
Can i set proxy？Otherwise, I will always report errors: Connection timed out: connect

**Comment by redouane59** [comment]
What do you mean exactly ?

**Comment by shiwangsimba** [comment]
like:
setProxy("xxx.xxx.xxx.xxx");
setPort("8080");

There may be some problems with my network. I can open twitter in Google, but the running code will report an error. It says that the connection time out. I found some solutions elsewhere, saying it is a proxy problem

![image](https://user-images.githubusercontent.com/65696505/134777382-09008aac-6a54-47cf-ba04-f477b43171f7.png)

**Comment by shiwangsimba** [comment]
![image](https://user-images.githubusercontent.com/65696505/134777460-ae07c6b8-b016-4c2f-b6cb-9ed92c5cef8b.png)
like this.This is the library of twitter 4J. I want to use the function of searching all tweets, but it doesn't have this function, so I replaced your library, but what's more embarrassing is that I can't use the proxy function

**Comment by redouane59** [comment]
Maybe you can set it up directly using your own HttpClient ?

Like `TwitterClient      twitterClient      = new TwitterClient(twitterCredentials, getServiceBuilder(twitterCredentials.getApiKey()));`

```
  private ServiceBuilder getServiceBuilder(String apiKey) {
    Builder httpBuilder = new Builder()
        .addNetworkInterceptor(new CacheInterceptor())
        // see if you can add here proxy info
    OkHttpHttpClient okHttpClient = new OkHttpHttpClient(new OkHttpHttpClientConfig(httpBuilder));
    return new ServiceBuilder(apiKey)
        .httpClient(okHttpClient);
  }
```

**Comment by shiwangsimba** [comment]
thank you , According to your prompt, I finally solved the problem like this
![image](https://user-images.githubusercontent.com/65696505/134795627-9bdbcfaa-c57a-4e8e-b499-0cafbb7c10c5.png)

but why I can get the data normally with "searchTweets", but the result returned by "searchAllTweets" is null

**Comment by redouane59** [comment]
Maybe because you don't have an authorised account ? Please check the error logs.

**Comment by shiwangsimba** [comment]
> Maybe because you don't have an authorised account ? Please check the error logs.

no,There is no error. When I use "searchTweets", the console outputs data, but when I use "searchAllTweets", there is no output, but the program runs normally without error. When I debug at breakpoint, I find that the value of result is null

**Comment by shiwangsimba** [comment]
![image](https://user-images.githubusercontent.com/65696505/134801879-18bcbae6-33f4-4808-a841-0005f47fd5a7.png)
![image](https://user-images.githubusercontent.com/65696505/134801909-d640a989-77be-4755-9d9b-b2db7ed6d830.png)

What I don't understand is that the strings I search are the same. Why do I use "searchTweets" and "searchAllTweets" have different results

**Comment by redouane59** [comment]
Because searchAllTweets is only for premium Twitter API accounts, and the time frame is not the same.
If you don't have a premium account, you won't be able to use this API. If you check the error logs you will see it.

**Comment by shiwangsimba** [comment]
> Because searchAllTweets is only for premium Twitter API accounts, and the time frame is not the same.
> If you don't have a premium account, you won't be able to use this API. If you check the error logs you will see it.

ok...I see. Thank you for your reply
