### ISSUE TITLE
Twitter Response Empty when Responding to Post?

### ISSUE THREAD

**Issue by marcphilippebeaujean-abertay** [redouane59/twittered#323]
I noticed that since updating to the latest build and using the new TwitterParameters builder, I've been getting back empty response body when replying to Tweets. Is this something with my code or changes in the code?

TweetParameters.Reply tweetReplyParams = TweetParameters.Reply
                .builder()
                .inReplyToTweetId(replyingToPostTwitterId)
                .build();
            TweetParameters tweetParameters = TweetParameters.builder()
                .reply(tweetReplyParams)
                .build();
            tweetFromApi = twitterClient.postTweet(tweetParameters);

**Comment by marcphilippebeaujean-abertay** [comment]
It was in fact my (frontend) code!

**Comment by MAkif06** [comment]
Hi,

I have the same error. When posting a tweet by using postTweet() method, tweet is posting but return object include just Id and Tweet text. For examplei I need tweet create date but return object retun null this value. How to get other ınformation from response object ?


![Issue](https://github.com/redouane59/twittered/assets/96817707/d17cd98c-5203-419e-afcd-09321caec530)
