### ISSUE TITLE
Implement OAuth 2.0 User Context management

### ISSUE THREAD

**Issue by redouane59** [redouane59/twittered#326]
See documentation [here](https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-context-making-requests-on-behalf-of-users)

**Comment by redouane59** [comment]
Hey @PhantomYdn , as you master this part, is it possible for you to submit a pull request with the implementation of the beta OAuth 2.0 announced by Twitter recently ?

**Comment by PhantomYdn** [comment]
@redouane59 , will try to find some spare time for that. You can assign this issue to me.

**Comment by redouane59** [comment]
> @redouane59 , will try to find some spare time for that. You can assign this issue to me.

Thank you so much !

**Comment by redouane59** [comment]
Hey @PhantomYdn , I would like to release the version 2.13 in the next following days, do you think you will have spare time to implement that before ?

**Comment by seinecle** [comment]
Allelujah! Will test it asap.

**Comment by redouane59** [comment]
Any new @PhantomYdn ?
