### ISSUE TITLE
Can't V2 send Tweet with pictures?

### ISSUE THREAD

**Issue by UoUoio** [redouane59/twittered#332]
Because my developer account only supports V2 API, when I call "twitterClient.uploadMedia ()", I will be prompted that I don't have permission to use this API. So I can't get the mediaId normally. I asked the relevant staff in the community, and they said that "the create tweet in v2 to post the tweet and attach the image" could be used to realize it. I studied for a day, but I couldn't find the relevant method in the project ... My English is poor, and I don't know if I misunderstood it. I'm really sorry to disturb you.

**Comment by redouane59** [comment]
Hey,

Please check the following example : https://github.com/redouane59/twittered/blob/develop/src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2AuthenticatedTest.java#L271

**Comment by UoUoio** [comment]
Thank you! ! !
