### ISSUE TITLE
Сan i get a list of tweets that a person has liked?

### ISSUE THREAD

**Issue by Programistich** [redouane59/twittered#342]

**Comment by redouane59** [comment]
This question is more for the twitter api forum. I don't think that such endpoint exists. For now you can only see the likes of an authenticated user.

**Comment by Programistich** [comment]
But Twitter have that api https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-favorites-list

**Comment by Programistich** [comment]
![image](https://user-images.githubusercontent.com/35292229/146244016-897bd212-f30c-452d-aaf9-3c152fdc7fbe.png)
![image](https://user-images.githubusercontent.com/35292229/146244040-a713a706-06ee-4d86-b2c8-db528096edbf.png)

**Comment by redouane59** [comment]
Sorry I was wrong, the authenticated is maybe not needed. Try to use `getLikedTweets` method !

**Comment by Programistich** [comment]
From User or what?

**Comment by redouane59** [comment]
From `TwitterClient` , it's a V2 method :)

**Comment by Programistich** [comment]
But i need to setup Oath2? How i can that in TwitterCredentials?

**Comment by redouane59** [comment]
You just need to instantiate the TwitterClient with your credentials yes.
Then you can check the example on the integration test : https://github.com/redouane59/twittered/blob/develop/src/test/java/io/github/redouane59/twitter/nrt/ITwitterClientV2Test.java#L460

**Comment by redouane59** [comment]
For the instantiation of the TwitterClient, check the readme : 
https://github.com/redouane59/twittered#readme

**Comment by redouane59** [comment]
Can I close this issue ?

**Comment by knutwannheden** [comment]
I just tested this method and it works. In the documentation it is mentioned that the endpoint supports pagination. But with this Java method I always get all liked tweets, which can be a lot and quite slow. Let me know if I should report a separate issue for this.

**Comment by knutwannheden** [comment]
Never mind, I missed the overload with the `AdditionalParameters` 🤦

**Comment by redouane59** [comment]
Don't worry haha, can we close the issue ?
