### ISSUE TITLE
Wrong FilteredStreamRulePredicate#and(FilteredStreamRulePredicate) implementation

### ISSUE THREAD

**Issue by oleg-grigorijan** [redouane59/twittered#344]
`And` operator in the Twitter query syntax looks like a single space `" "`, not `" AND "`. 
`" AND "` is interpreted as "filter tweets containing `AND` keyword"

See [Boolean operators and grouping](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#boolean) section.
Also see a [warning here](https://developer.twitter.com/apitools/query?query=a2V5d29yZEEgQU5EIGtleXdvcmRC):
> An uppercase 'AND' will be interpreted as a keyword. For AND logic, use a single whitespace ' ' between clauses

**Comment by redouane59** [comment]
Thanks for the feedback ! @rzo1 could you submit a Pull Request to fix it please ?

**Comment by rzo1** [comment]
Thanks for the heads up @oleg-grigorijan - cool, that someone is using it. @redouane59 I just submitted a PR, which replaces the ` AND ` with the ` ` to respect twitter query syntax.

**Comment by oleg-grigorijan** [comment]
Thanks for your speed 👍🏻
