### ISSUE TITLE
getUserTimeline method issue

### ISSUE THREAD

**Issue by cjkipu** [redouane59/twittered#350]
![image](https://user-images.githubusercontent.com/43841454/148265715-8fbf502f-4368-47b4-818b-976435a8de96.png)

Getting the output above when invoking the getUserTimeline method instead of the tweet id and text

**Comment by cjkipu** [comment]
This is the code used when using the method
TweetList userTimeline = twitterClient.getUserTimeline(id);
                List<TweetV2.TweetData> tweetList = userTimeline.getData();

                for (int i = 0; i<tweetList.size(); i++) {
                    String nu = tweetList.get(i).toString();
                    Log.d("tweet Content", nu);
                }

**Comment by redouane59** [comment]
`tweetList.get(i)` gives you a `Tweet` not a `String`. You should try `nu.getText()` instead.

**Comment by cjkipu** [comment]
`tweetList.get(i).getText().toString()` worked. 
Thanks for your help
