### ISSUE TITLE
startFilteredStream without filters set?

### ISSUE THREAD

**Issue by consal** [redouane59/twittered#351]
Hello! Is it possible to use `startFilteredStream` without setting filters before (with `addFilteredStreamRule`)? For me, if there are no filters, there is no response at all. In CLI, trying with curl and no filters, it returns plenty of tweets.
`curl -X GET -H "Authorization: Bearer $BEARER_TOKEN" "https://api.twitter.com/2/tweets/sample/stream"`

**Comment by redouane59** [comment]
Hello @consal , honestly I never tested this use case before, if it is working from CLI but not in the library, that's probably a bug. I'm in travel right now but I'll try to check in the next following days :à

**Comment by redouane59** [comment]
I didn't find anything in the code who can explain that.
Just created a post on Twitter Forum there :
https://twittercommunity.com/t/filtered-stream-without-rules/164922

**Comment by igorbrigadir** [comment]
The sample stream is a different endpoint, and returns random 1% of all public tweets, while the filter stream returns tweets that match the rules only. If there are no rules or you delete rules while the stream is open, I think it just sends nothing.

**Comment by redouane59** [comment]
Ohhh well seen @igorbrigadir ! @consal you were looking for another method, which is `startSampledStream` no ?

**Comment by consal** [comment]
Oh, nice! Let me try the sampled stream and I'll let you know if it works!

**Comment by consal** [comment]
Unfortunately the Sampled stream doesn't seem to work, the code:

```java
TwitterClient twitterClient = new TwitterClient(TwitterCredentials.builder()
            .bearerToken(bearerToken).build());

Future<Response> future = twitterClient.startSampledStream((Tweet tweet) -> {
            logger.info("from:@" + tweet.getUser().getName() + " : " + tweet.getText());
            producer.send(new ProducerRecord<>(topicName, tweet.getText()), (recordMetadata, e) -> {
                if (e != null) {
                    logger.error("Something bad happened!", e);
                }
            });
        });
```

The stream doesn't return anything, it immediately returns. Adding `future.get()` doesn't change anything

**Comment by redouane59** [comment]
Juste made this test on my side and it works : 
Simply use : 
```
twitterClient.startSampledStream(tweet -> System.out.println(tweet.getText()));
```

**Comment by consal** [comment]
Today I reran exactly the same code and it's working 😅
No idea what I was doing wrong yesterday. Anyway, thanks so much for your help!
