### ISSUE TITLE
List of APIs missing

### ISSUE THREAD

**Issue by suyashjoshi** [redouane59/twittered#390]
Is there an API list or API Docs like JavaDoc that explains which of the Twitter APIs are present in this library without reading all the code?

**Comment by redouane59** [comment]
Hello,
Currently the available APIs are only visible in 
https://github.com/redouane59/twittered/blob/develop/src/main/java/io/github/redouane59/twitter/ITwitterClientV2.java
and
https://github.com/redouane59/twittered/blob/develop/src/main/java/io/github/redouane59/twitter/ITwitterClientV1.java
classes.

Don't hesitate to submit a pull request if you would like to present it differently, it will probably help other developers.

**Comment by suyashjoshi** [comment]
Got it buddy, thanks!
