### ISSUE TITLE
How to avoid shadowbans

### ISSUE THREAD

**Issue by mikebgrep** [redouane59/twittered#392]
I thinking of using the library I just have concern of Twitter shadowban my account.How can avoid that since I build a bot with python and I got shadowbans after each run.

**Comment by redouane59** [comment]
Hey @mikebgrep , if you respect the [twitter developer policy](https://developer.twitter.com/en/developer-terms/policy), you don't risk anything :)

**Comment by mikebgrep** [comment]
They dont like mass following of accounts that's is sure.I will try to scale the action so they don't shadowban me again. Thanks for the replay.
