### ISSUE TITLE
response.getHeader("Retry-After") This is not the rate limit return parameter for the v1.1 and v2 interfaces

### ISSUE THREAD

**Issue by quyingyong** [redouane59/twittered#408]
![image](https://user-images.githubusercontent.com/12825648/194742110-27a63dae-fc76-4bf2-835f-bb81b0e38c3e.png)

This is the correct return parameter ↓↓↓↓↓↓↓↓↓↓
![image](https://user-images.githubusercontent.com/12825648/194742125-f5d3e366-5e56-4c13-97ed-2e9859f1a689.png)

**Comment by redouane59** [comment]
Hey, could you submit a pull request with the fix and the associated test ?

**Comment by blizniukov** [comment]
Created PR

**Comment by redouane59** [comment]
fixed
