### ISSUE TITLE
V2.19 BUG 

### ISSUE THREAD

**Issue by lichao23** [redouane59/twittered#411]
![338241665542864_ pic](https://user-images.githubusercontent.com/5652276/195238976-6814030b-b020-4f94-bbbe-1b777b087de7.jpg)
v2.18 works fine, but updates to v2.19 have this problem

**Comment by redouane59** [comment]
Hey @blizniukov , could you check this one ? I guess it's related to your PR https://github.com/redouane59/twittered/pull/403

**Comment by blizniukov** [comment]
done

**Comment by lichao23** [comment]
@blizniukov @redouane59 Can a new version of this issue be released soon? We've been at a standstill for days

**Comment by redouane59** [comment]
> @blizniukov @redouane59 Can a new version of this issue be released soon? We've been at a standstill for days

Hey, I'm going to try to deploy a new version today or tomorrow.

**Comment by redouane59** [comment]
Done !
