### ISSUE TITLE
.searchTweets(query)  return data format exceeded the expected formatting failed

### ISSUE THREAD

**Issue by quyingyong** [redouane59/twittered#422]
.searchTweets(query)  

When this interface is invoked, the data format returned is as follows

![image](https://user-images.githubusercontent.com/12825648/199876451-25fd7e09-f39d-460a-814d-a4ef02009378.png)

Different query parameters may return data items that do not meet expectations
Therefore, json formatting of the returned data for the searchTweets method needs to be compatible 
![image](https://user-images.githubusercontent.com/12825648/199876678-f6237ca6-ebd9-4a7e-a87a-39ba23cb3b57.png)

**Comment by quyingyong** [comment]
Can you import it in a pom file ？

![image](https://user-images.githubusercontent.com/12825648/199901427-15dd9cf4-5acb-4f63-8234-fa24b718ae92.png)

**Comment by redouane59** [comment]
Hello @quyingyong , why did you close the ticket ? Is it not working now ?
