### ISSUE TITLE
Unauthorized 401 follow request 

### ISSUE THREAD

**Issue by mikebgrep** [redouane59/twittered#430]
I try to follow with the library and its return me Status Code 401 Unauthorized. I think the library is super for use simple and effective.
I also try with my costume requests with Scribe and the result is same I don't know where I am wrong as I use the same api keys and account from my Python script and is working well, the problem must be in Java.Somebody any clue why is return my this response for all POST requests is appear on GET users/me the authorization is working The project is Spring Boot application.I am wondering if I need to do in developer portal.

`2023-01-15 14:27:48.113 ERROR 9278 --- [nio-8080-exec-6] i.g.r.t.helpers.AbstractRequestHelper    : (POST) Error calling https://api.twitter.com/2/users/15126750405812327553/following {
  "title": "Unauthorized",
  "type": "about:blank",
  "status": 401,
  "detail": "Unauthorized"
} - 401`

**Comment by redouane59** [comment]
Are you sure to correctly use your twitter api credentials ?

**Comment by mikebgrep** [comment]
Yes the credentials are correct I double check I am wondering that do spring security do something with the request.From my python script working okay but with Scribe stand alone or with twittered I got 401 Unautorized any ideas.

**Comment by mikebgrep** [comment]
Okay I create new spring boot project and is appear is working from there.

**Comment by mikebgrep** [comment]
Closing the issue resolved
