### ISSUE TITLE
Rate limit exceeded on search of user followings amount of 40

### ISSUE THREAD

**Issue by mikebgrep** [redouane59/twittered#432]
I see this helper is got activated for search of user followings for result of 40 users I try to debug and see where is the problem, but I didn't spot something maybe someone familiar with the project could take a look from this I see its send parameter for max_results of 40, but I don't know why the rate limit is triggered for that low result as in Postman is working fine. I think it needs to be checked.

`i.g.r.t.helpers.AbstractRequestHelper    : Rate limit exceeded, new retry ....` 

`amount = 40;`
```
 public List<UserV2.UserData> getUserFollowing(String userId, int amount) {
        AdditionalParameters parameters = AdditionalParameters.builder()
                .maxResults(amount)
                .build();

        UserList following = twitterClient().getFollowing(userId, parameters);
        List<UserV2.UserData> data = following.getData();

        return data; 
```

**Comment by redouane59** [comment]
If you have a rate limit response, it is because the Twitter API was called too much by your account, there is no relation with the library.

See here : https://developer.twitter.com/en/docs/twitter-api/rate-limits

**Comment by mikebgrep** [comment]
The future is good I am closing the issue  to not spam.Thank
