### ISSUE TITLE
mvnrepository not updated

### ISSUE THREAD

**Issue by akuma0** [redouane59/twittered#438]
Hi !
The maven repo isn't update since the version 1.26 (Jun 01, 2021) do you plan to update artifact with new versions ?

**Comment by redouane59** [comment]
Hello,

If you need a new version for a concrete purpose just let me know, I'll try to do it on the next days. 
But as far as Twitter API will stop to be free, I'm not sure to put many energy on this library that 99% of users will stop using.

**Comment by akuma0** [comment]
That's only to get all new features and optimisations since the 1.26.
I hope Musk will change his mind about Twitter API !

**Comment by redouane59** [comment]
done :)
