### ISSUE TITLE
Any documentation on the Twitter Stream functions?

### ISSUE THREAD

**Issue by DxsSucuk** [redouane59/twittered#447]
Hey there!
I am switching over from Twitter4J since it is some sort of dead because the Twitter API v1.1 has been shutdown not too long ago.
I got recommended to use this library instead and would love to do so!
Sadly I do not understand how to exactly listen to muliple user twitter streams.
By that I mean making a consumer/event handler, which handles the tweets by random users that are not being followed by the Twitter account itself.

Is that even possible with V2?

Thanks in advanced for the response!

**Comment by redouane59** [comment]
Hello,
Yes you can simply use rules. Check : https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/build-a-rule
