### ISSUE TITLE
Improve Search Tweets endpoints

### ISSUE THREAD

**Issue by redouane59** [redouane59/twittered#46]
Currently the methods like `searchForTweetsWithin7days` only allow to get a fix result size (100). It would be better to give the user the possibility to make several calls using a `next_token` got on the method turn to retrieve more tweets.

@sparack

**Comment by redouane59** [comment]
I've got a big difficulty here, if I want to conserve the method signature (`List<Tweet> searchForTweetsWithin7days(String query, LocalDateTime fromDate, LocalDateTime toDate)`), I won't be able to return the `next_token` data in addition. 
2 solutions : 
1/ return a `Tuple<List<Tweet>, String>` using vavr
2/ return a new object `TweetSearchResponse` which will contain a field with `List<Tweet> tweets` and another field with `String nextToken` ...

**Comment by hypr2771** [comment]
What is the functional use of `next_token`?
Could you instead give the API user a context from which he can keep on launching request?
For instance, in standard Spring Data JPA one can use `Pageable` in order to give an indicator of the current page to request, as well exposing a way to easily query the next page.

**Comment by RedouaneBALI** [comment]
I think that this is the same that what you have in mind : 
> `next_token` : This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.
[source](https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction)

Basically the user could decide to launch his request adding the `next_token` argument to continue requesting from the last tweet he reached on the previous call.

**Comment by redouane59** [comment]
I think that this is the same that what you have in mind : 
> `next_token` : This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.
[source](https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction)

Basically the user could decide to launch his request adding the `next_token` argument to continue requesting from the last tweet he reached on the previous call.
