### ISSUE TITLE
Nullpointer exception on getTweetType()

### ISSUE THREAD

**Issue by psoares** [redouane59/twittered#63]
When invoking TweetV2::getTweetType, I sometimes get a NullPointerException.
Example tweet currently causing the issue:
![image](https://user-images.githubusercontent.com/192243/92522798-4aa39880-f1ed-11ea-988e-598844c4f763.png)

**Comment by redouane59** [comment]
Hi @psoares ,
Thanks for the feedback !
You're right, my implementation for this method is really bad and should never return a null value. I will update it to return something like `TweetType.DEFAULT` if the API doesn't provide the `referenced_tweets`.

**Comment by redouane59** [comment]
Fix was merged on the develop branch. It will be included on the next release ;)

Thanks again for your feedback !

**Comment by redouane59** [comment]
Fixed in `v1.10`. If you have any other problem, please let me know.
