### ISSUE TITLE
Choose a codestyle for the project and update code accordingly

### ISSUE THREAD

**Issue by jkolobok** [redouane59/twittered#78]

**Comment by redouane59** [comment]
@hypr2771 i'm using the Google one that you pushed me. What do you advice me to add on the repo to make it clear for all ?

**Comment by hypr2771** [comment]
> @hypr2771 i'm using the Google one that you pushed me. What do you advice me to add on the repo to make it clear for all ?

You should just make it shared within the code base. There is a checkbox you can tick right side code style name to make it shared.
Do check your `.gitignore` to ensure you are not ignoring it.

I am on my phone ATM, can't give you more details. If you still don't find how to, I'll give more details later today.

**Comment by redouane59** [comment]
Solved by https://github.com/redouane59/twittered/pull/80
