### ISSUE TITLE
Option to get additional fields in Sampled Stream api

### ISSUE THREAD

**Issue by vishva007** [redouane59/twittered#81]
Is it possible to add a feature to send different get parameters to the request as the samples stream provides these features ?

I see that in the class [URLHelper.java](https://github.com/redouane59/twittered/blob/develop/src/main/java/com/github/redouane59/twitter/helpers/URLHelper.java) , getFilteredStreamUrl() already has these fields appended. 

I am using a local build currently for these fields. I can submit a pull request with these changes if it is ok. 

Refer: https://developer.twitter.com/en/docs/twitter-api/tweets/sampled-stream/api-reference/get-tweets-sample-stream

**Comment by redouane59** [comment]
Hi @vishva007 , yes it's ok you can submit a pull request with this evolution. I'm really busy because I'm currently moving to another country so my developments are temporary stopped but if you have time to develop it we will be happy to check it :)

**Comment by redouane59** [comment]
Finally i think it's almost nothing. Can you check https://github.com/redouane59/twittered/pull/82 and tell me if it looks ok for you ?

**Comment by vishva007** [comment]
The pr is good. These are same changes what I did locally. 

For a long term point of view, maybe adding a feature to set custom enum fields for the request would optimize some load. 
I will work on this over the weekend and try to submit a pr. 

Thank you

**Comment by redouane59** [comment]
> I will work on this over the weekend and try to submit a pr.

Yes with pleasure, that's something I had in my mind but I never had the time to implement it so you're welcome !
