### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by mattes3** [redouane59/twittered#84]
Hi folks,
this is real good software. Is it open source? If so, could you please add an open source license so that I know how I may use this library?

Best...
Matthias

**Comment by redouane59** [comment]
Hi Matthias,
Yes it's open source :) 
I'm currently out of home for several days but if you want to submit a PR with a licence file don't hesitate. Otherwise i'll check this topic next month.

**Comment by redouane59** [comment]
Solved by https://github.com/redouane59/twittered/pull/85
