### ISSUE TITLE
User attributes: name x screen_name x username

### ISSUE THREAD

**Issue by michelazzo** [redouane59/twittered#87]
In the version [1.0 of the user's object model](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview/user-object), I see those fields related with the user's name:
- name (ex. "name": "Twitter API")
- screen_name (ex. "screen_name": "twitterapi")

Then in the version [2.0 of the user's object model](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/user), those are the attributes:
- name (ex. "name": "Twitter Dev")
- username (ex. "username": "TwitterDev", same as `screen_name` of the version 1.0).

The problem is the Java DTO has only one attribute `name` mapped to the JSON attributes `screen_name` and `username`, meaning the JSON attribute `name` is being ignored and the first ones are wrongly mapped.

My suggestion is mapping the JSON attributes `screen_name` and `username` to the Java DTO `username` and map the JSON attribute `name ` to a new DTO attribute `name`.

**Comment by redouane59** [comment]
Hi @michelazzo , good point. I will try to watch it this week-end.

**Comment by redouane59** [comment]
Hi again, it's ok, already fixed ! Will be available soon in the new version 1.13 currently releasing.

**Comment by michelazzo** [comment]
Wow, that was fast! Thanks @redouane59 :)

**Comment by redouane59** [comment]
> Wow, that was fast! Thanks @redouane59 :)

You're welcome ! :)
