### ISSUE TITLE
Ability to block users

### ISSUE THREAD

**Issue by elle-trudgett** [redouane59/twittered#95]
Is the ability to block a user part of the current functionality?

**Comment by redouane59** [comment]
Hi,

Currently this function is not implemented. Moreover, it only exists in Twitter API v1.1 : https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create

As soon as it will be available in Twitter API V2, I'll implement it. Or if you just want to submit a pull request, feel free :)

**Comment by elle-trudgett** [comment]
Got it. Thanks!

**Comment by redouane59** [comment]
Hi @elle-trudgett , the feature is now available in v1.22 :) 
See https://github.com/redouane59/twittered/pull/162

**Comment by elle-trudgett** [comment]
that's great, thank you!
